<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart */
/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?php /* @escapeNotVerified */ echo $block->getLayout()->renderElement($childName, false); ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
    
    <?php if ($product->isSaleable()): ?>
        <?php if ($product->getTypeId() == 'simple'):?>
        <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()): ?>
            <div class="field qty">
                <label class="label" for="qty[<?php /* @escapeNotVerified */ echo $item->getId() ?>]"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                <div class="control">
                    <button type="button"  class="minus"><i class="icon-minus"></i></button>
                    <input type="number" data-role="qty" id="qty[<?php /* @escapeNotVerified */ echo $item->getId() ?>]" class="input-text qty" data-validate="{'required-number':true,'validate-greater-than-zero':true}"
                   name="qty[<?php /* @escapeNotVerified */ echo $item->getId() ?>]" value="<?php /* @escapeNotVerified */ echo $block->getAddToCartQty($item) * 1 ?>">
                   <button type="button"  class="plus"><i class="icon-plus"></i></button>
                </div>
            </div>
        <?php endif; ?>
        <div class="product-item-actions">
            <div class="actions-primary">
                <button type="button" data-role="tocart" data-post='<?php /* @escapeNotVerified */ echo $block->getItemAddToCartParams($item)?>' title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" data-item-id="<?php /* @escapeNotVerified */ echo $item->getId()?>" class="action primary tocart btn btn-default  btn-product btn-cart">
                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                </button>
            </div>
        </div>
        <?php else: ?>
        <div class="product-item-actions">
            <div class="actions-primary">
                <a class="select-option action primary tocart btn btn-default  btn-product btn-cart" href="<?php echo $product->getProductUrl(); ?>">Select option</a>
            </div>
        </div>
        <?php endif; ?> 
    
    <?php else: ?>
        <?php if ($product->getIsSalable()): ?>
            <p class="available stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
            </p>
        <?php else: ?>
            <p class="unavailable stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
            </p>
        <?php endif; ?>
    <?php endif; ?>
    </fieldset>
</div>
