<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Ctq\Block\Customer\Quote\Edit\Item */
/** @var \Aheadworks\Ctq\ViewModel\Email\Quote\Item\DefaultRenderer $viewModel */
$viewModel = $block->getViewModel();

// @codingStandardsIgnoreFile
?>
<?php
$item = $block->getItem();
$itemProduct = $item->getProduct();
$itemOptions = $viewModel->getOptionList($item);
$itemId = $item->getId();
?>
<tr>
    <td class="col name <?= (empty($itemOptions) ? '' : ' has-extra') ?>" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <div class="product-item-photo">
            <?= /* @noEscape */ $viewModel->getProductImageHtml($item) ?>
        </div>
        <div class="product-item-details">
            <p class="product-name"><?= $block->escapeHtml($itemProduct->getName()) ?></p>
            <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($itemProduct->getSku()) ?></p>
            <?php if ($itemOptions): ?>
                <dl class="item-options">
                    <?php foreach ($itemOptions as $itemOption): ?>
                        <?php $formattedOptionValue = $viewModel->getFormattedOptionValue($itemOption) ?>
                        <dt><?= $block->escapeHtml($itemOption['label']) ?></dt>
                        <dd>
                            <?php if (isset($formattedOptionValue['full_view'])): ?>
                                <?= /* @noEscape */ $formattedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?= $block->escapeHtml($formattedOptionValue['value'], ['span']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $viewModel->getMessages($item)): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="item message <?= /* @noEscape */ $message['type'] ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= /* @noEscape */ $block->getUnitPriceHtml($item) ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <?= /* @noEscape */ $block->getQty() ?>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= /* @noEscape */ $block->getRowTotalHtml($item) ?>
    </td>
</tr>
