<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Customer\Sidebar */
?>
<?php
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
?>
<?php if ($wishlistHelper->isAllow()) : ?>
    <div class="block block-wishlist" data-bind="scope: 'wishlist'">
        <button id="close-wishlist-site" class="close-wishlist-site"><span class="icon-close"></span></button>
        <?php $isLogged = $this->helper('Aventi\ManagerPrice\Helper\Data')->_getIsLogged();
        if($isLogged): ?>
            <!-- ko if: wishlist().counter -->
                <div class="block-content">
                    <ol class="product-items no-display" id="wishlist-sidebar" data-bind="foreach: wishlist().items, css: {'no-display': null}">
                        <li class="product-item">
                            <div class="product-item-info">
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a data-bind="attr: { href: product_url }" class="product-item-link">
                                            <span data-bind="text: product_name"></span>
                                        </a>
                                    </strong>
                                    <div data-bind="html: product_price"></div>
                                    <div class="product-item-actions">
                                        <!-- ko if: product_is_saleable_and_visible -->
                                        <div class="actions-primary">
                                            <!-- ko if: product_has_required_options -->
                                            <a href="#" data-bind="attr: {'data-post': add_to_cart_params}" class="action tocart primary btn-xs"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></a>
                                            <!-- /ko -->
                                            <!-- ko ifnot: product_has_required_options -->
                                                <button type="button" class="action tocart primary btn-xs" data-bind="attr: {'data-post': add_to_cart_params}"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></button>
                                            <!-- /ko -->
                                        </div>
                                        <!-- /ko -->
                                        <div class="actions-secondary">
                                            <a href="#"  data-bind="attr: {'data-post': delete_item_params}"
                                            title="<?php /* @escapeNotVerified */ echo __('Remove This Item') ?>"
                                            class="btn-remove action delete">
                                                <span><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
                                    <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                                </a>
                            </div>
                        </li>
                    </ol>
                    <div class="actions-toolbar no-display" data-bind="css: {'no-display': null}">
                        <div class="primary">
                            <a class=" btn btn-default"
                            href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Wishlist\Helper\Data')->getListUrl() ?>"
                            title="<?php /* @escapeNotVerified */ echo __('All Wish List') ?>"><?php /* @escapeNotVerified */ echo __('All Wish List') ?></a>
                        </div>
                    </div>
            </div>
            <!-- /ko -->
            <!-- ko ifnot: wishlist().counter -->
                <div class="block-content empty">
                    <div class="empty"><?php /* @escapeNotVerified */ echo __('You have no items in your wish list.') ?></div>
                </div>
            <!-- /ko -->
        <?php else: ?>
            <div class="block-content wishlist-placeholder">
                <svg width="100%" viewBox="0 0 225 83" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect x="0.4375" width="156" height="15" rx="7.5" fill="#EBEBEB"/>
                    <rect x="176.562" y="9" width="48" height="40" fill="#EBEBEB"/>
                    <rect x="0.4375" y="22" width="134" height="15" rx="7.5" fill="#EBEBEB"/>
                    <rect x="0.4375" y="75" width="59" height="8" rx="4" fill="#EBEBEB"/>
                    <rect x="0.4375" y="44" width="152" height="15" rx="7.5" fill="#EBEBEB"/>
                </svg>
                <div class="wishlist-placeholder__container">
                    <p><?php /* @escapeNotVerified */ echo __('You must have an account to save products.') ?></p>
                    <div class="wishlist-placeholder__container__actions">
                        <a class="wishlist-placeholder__container__actions__link" href="http://www.aventidev.local/magento/siglo21/customer/account/create/" title="Iniciar sesión">
                            <span class="label">
                                Iniciar sesión
                            </span>
                        </a>
                        <a class="wishlist-placeholder__container__actions__link register-link" href="http://www.aventidev.local/magento/siglo21/customer/account/create/" title="Solicitar registro">
                            <span class="label">
                                Solicitar registro
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        <?php endif ?>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
<?php endif ?>
