<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
            
            <div class="field qty">
                <label for="qty">Qty:</label>
                <div class="qty-pr">
                    <div class="input-group-prepend">
                        <button style="min-width: 26px" class="edit-qty minus disable-select-text btn btn-decrement btn-spinner" onclick="minusQty('qty')" type="button">
                            <i class="icon-minus"></i>
                        </button>
                    </div>
                    
                    <input type="number"
                           name="qty"
                           id="qty"
                           maxlength="12"
                           value="<?= $block->getProductDefaultQty() * 1 ?>"
                           title="<?= __('Qty') ?>" class="input-text qty"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                           />
                    <div class="input-group-append">
                        <button style="min-width: 26px" class="edit-qty plus disable-select-text btn btn-increment btn-spinner" onclick="plusQty('qty')" type="button">
                            <i class="icon-plus"></i>
                        </button>
                    </div>
                </div>
            </div>

            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart btn btn-default  btn-product btn-cart"
                        id="product-updatecart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
            </div>
            <?php echo $block->getChildHtml('', true) ?>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
    <?php if ($block->shouldRenderQuantity()): ?>
        <script type="text/javascript">
            function plusQty(qtyInput){
                require([
                'jquery'
                ], function($){
                    if($('#'+qtyInput).attr('disabled')!='disabled'){
                        qty = $('#'+qtyInput).attr('value');
                        qty = parseInt(qty);
                        qty++;
                        $('#'+qtyInput).val(qty);
                        $('#sticky_qty').val(qty);
                    }
                });
                
            }
            function minusQty(qtyInput){
                require([
                'jquery'
                ], function($){
                    if($('#'+qtyInput).attr('disabled')!='disabled'){
                        qty = $('#'+qtyInput).attr('value');
                        qty = parseInt(qty);
                        
                        if(qty>1){
                            qty--;
                            $('#'+qtyInput).val(qty);
                            $('#sticky_qty').val(qty);
                        }
                    }
                });
            }
        </script>
    <?php endif; ?>

<?php endif; ?>
