<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
<a href="<?= $block->escapeUrl($block->getPrintUrl()) ?>" class="custom__print" target="_blank" rel="noopener">
    <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M5 8V1H17V8" stroke="#E41F13" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
        <path
            d="M5 17H3C2.46957 17 1.96086 16.7893 1.58579 16.4142C1.21071 16.0391 1 15.5304 1 15V10C1 9.46957 1.21071 8.96086 1.58579 8.58579C1.96086 8.21071 2.46957 8 3 8H19C19.5304 8 20.0391 8.21071 20.4142 8.58579C20.7893 8.96086 21 9.46957 21 10V15C21 15.5304 20.7893 16.0391 20.4142 16.4142C20.0391 16.7893 19.5304 17 19 17H17"
            stroke="#E41F13" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
        <path d="M17 13H5V21H17V13Z" stroke="#E41F13" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
    </svg>
    <p>
        <?= $block->escapeHtml(__('Print receipt')) ?>
    </p>
</a>
<?= $block->getChildHtml() ?>
<?php endif;?>