 <?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Checkout\Block\Item\Price\Renderer */
$isLogged = $this->helper('Aventi\ManagerPrice\Helper\Data')->_getIsLogged();
?>
<?php $_item = $block->getItem() ?>
<?php if ($isLogged) :?>
  <div class="price-container">
    <span class="price-label"><?= $block->escapeHtml(__('Price')) ?></span>
    <span class="price-wrapper">
          <?= $block->escapeHtml(
    $this->helper(Magento\Checkout\Helper\Data::class)->formatPrice($_item->getCalculationPrice()),
    ['span']
) ?>
      </span>
  </div>
<?php endif; ?>
