<?php

use Magento\Framework\App\Action\Action;

$dataHelper = $this->helper('MGS\AjaxCart\Helper\Data');
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$viewMode = 'grid';
$image = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$_product = $this->getProduct();
if ($_product != false && !empty($_product)) {
	$_productNameStripped = $block->stripTags($_product->getName(), null, true);
	$_productImage = $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setProduct($_product)->setTemplate('MGS_Amp::Magento_Catalog/product/image_custom.phtml')->toHtml();
}

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$configHelper = $this->helper('MGS\ThemeSettings\Helper\Config');
?>
<?php $_configAmpHelper = $this->helper('MGS\Amp\Helper\Configurable'); ?>
<?php if ($_product != false && !empty($_product) && $_product->getId()) : ?>
	<div class="block widget mgs-product single-deal products-grid product-items product-item">
		<div class="product-item-info">
			<?php $_productUrl = $block->getProductUrl($_product); ?>
			<?php $_productName = $block->escapeHtml($_product->getName()); ?>
			<a class="product photo product-item-photo" href="<?= $_productUrl ?>?amp=1" title="<?= $_productName ?>">
				<?= $_productImage ?>
			</a>
			<div class="product-item-details">
			<?php if ($this->getData('sub_title')) : ?>
				<div class="product label">
					<div class="sub-title"><?= $this->getData('sub_title'); ?></div>
				</div>
			<?php endif ?>

			<?= $block->getProductPrice($_product); ?>
			<span class="text-price-label">
				<?php echo __('Price without TAX') ?>
			</span>
			<div class="product actions product-item-actions">
				<?php if($_product->isSaleable() && (($_product->getTypeId()=='simple' && !$_product->getTypeInstance()->hasOptions($_product)) || ($_product->getTypeId()=='configurable'))): ?>
					<div class="product-add-form">
						<form custom-validation-reporting="show-all-on-submit" action-xhr="<?php /* @escapeNotVerified */ echo str_replace('http:', '',$block->getUrl('amp_api/cart/add')) ?>" method="post"
							  id="product_addtocart_form<?php echo $_product->getId() ?>"
							  on="submit-success:ampminicart.refresh,amptotalcart.refresh,lightboxMessage<?php echo $_product->getId() ?>">
							<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
							<?php echo $_configAmpHelper->getAmpJsonOption($_product, '') ?>

							<amp-lightbox id="lightboxMessage<?php echo $_product->getId() ?>" layout="nodisplay" class="product-alert">
								<div class="lightbox" role="button" tabindex="0" on="tap:lightboxMessage<?php echo $_product->getId() ?>.close">
									<div submit-success>
										<template type="amp-mustache">
											{{^error}}
											<div class="message success">
												{{success}}
											</div>
											{{/error}}
											{{^success}}
											<div class="message error">
												{{error}}
											</div>
											{{/success}}

										</template>
									</div>
								</div>
							</amp-lightbox>

							<button class="button btn-cart action tocart" type="submit"><span><?= __('Add to Cart'); ?></span></button>
						</form>
					</div>
				<?php else: ?>
					<div class="actions-primary">
						<a href="<?= $_productUrl ?>" class="action tocart"><span><?= __('View Detail'); ?></span></a>
					</div>
				<?php endif ?>
			</div>
			</div>
		</div>

	</div>
<?php else : ?>
	<div class="message info empty">
		<div><?= /* @escapeNotVerified */ __('There are no products matching the selection.') ?></div>
	</div>
<?php endif ?>
