<?php
$_storeCollection = $this->getStoreCollection();

$totalStoreCount = count($_storeCollection);
$markers = $agruments = array();
$curPage = 1;
if($this->getRequest()->getParam('p', false)) {
    $curPage = $this->getRequest()->getParam('p', false);
}
$agruments['p'] = $curPage;
?>
<?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<div class="store-list-container store-list-contact">
    <?php if ($totalStoreCount): ?>
        <div class="store-list">
            <div class="store-list-items">

                <h2 class="title text-center mb-3"><?= __('Our Stores') ?></h2>
                <div class="items">
                    <div class="stores owl-carousel">
                        <?php $i = 0; foreach ($_storeCollection as $store): $i++; ?>

                            <?php $markers[$i]['name'] = '<div class="map-short-info"><h3>' . $store->getName() . '</h3><p>'; ?>
                            <?php $markers[$i]['lat'] = $store->getLat(); ?>
                            <?php $markers[$i]['long'] = $store->getLng(); ?>
                            <div class="item-store-locator">
                                <div class="store-logo">
                                    <a class="images-store" href="<?= $block->getUrl('locator/index/view', ['id' => $store->getId()]); ?>" title="<?= $store->getName(); ?>">
                                        <img src="<?= $this->getImageUrl($store->getlogoStore()) ?>" alt="<?= $store->getName(); ?>"/>
                                    </a>
                                </div>
                                <div class="store-infor">
                                    <h4><a href="<?= $block->getStoreUrlKey($store); ?>"><?= $store->getName() ?></a></h4>
                                    <address>
                                        <?= $store->getStreetAddress() ?>
                                    </address>

                                    <?php $markers[$i]['name'] .= '</p>'; ?>

                                    <?php if ($store->getPhoneNumber()): ?>
                                        <p class="store-phone"><?= __( $store->getPhoneNumber()) ?></p>
                                    <?php endif; ?>

                                    <?php if($store->getTrading_hours()): ?>
                                        <h4 class="store-subtitle">Store Hours:</h4>
                                        <?php echo $store->getTrading_hours(); ?>
                                    <?php endif; ?>

                                    <?php $markers[$i]['name'] .= '<p><a href="' . $block->getUrl('locator/index/view', ['id' => $store->getId()]) . '">' . __('Details') . '</a></p>'; ?>

                                    <?php $markers[$i]['name'] .= '</div>'; ?>

                                    <?php if ($store->getLat() && $store->getLng()): ?>
                                        <a
                                            onclick="initializeMap(<?= $store->getLat(); ?>, <?= $store->getLng(); ?>, <?= $this->getRadius($store); ?>,'<?= str_replace('"', '-quotation-', $markers[$i]['name']); ?>', 'store-list-map');"
                                            class="btn btn-link icon-right" title="<?= __('View Map') ?>" type="button">
											<span>
											<?= __('View Map') ?>
											</span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif ?>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'mgsowlcarousel'
    ], function ($) {
        $('.owl-carousel').owlCarousel({
            items: 2,
            autoplay: false,
            autoplayHoverPause: true,
            nav: false,
            dots: true,
            loop: true,
            margin: 10,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:1
                },
                992:{
                    items:2
                }
            }
        });
    });
</script>