<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/** @var Magento\Framework\View\Element\Template $block */

/** @var \Aheadworks\Ca\ViewModel\Adminhtml\Customer\CompanyInformation $companyInformation */
$companyInformation = $block->getViewModel();

?>
<tr>
    <th><?= $block->escapeHtml(__('Company:')) ?></th>
    <td><?= $block->escapeHtml($companyInformation->getCompanyName()) ?></td>
</tr>
<tr>
    <th><?= $block->escapeHtml(__('Status in Company:')) ?></th>
    <td><?= $block->escapeHtml($companyInformation->getStatusInCompany()) ?></td>
</tr>
<tr>
    <th><?= $block->escapeHtml(__('Job Position:')) ?></th>
    <td><?= $block->escapeHtml($companyInformation->getJobPosition()) ?></td>
</tr>