<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Ca\Block\Role\RoleList */

// @codingStandardsIgnoreFile

$roleList = $block->getRoleListViewModel()->getSearchResults()->getItems();
$roleViewModel = $block->getRoleViewModel();
?>
<?php if ($roleList && count($roleList)): ?>
    <div class="table-wrapper aw-ca__customer-roles">
        <table class="data table">
            <caption class="table-caption">
                <?= $block->escapeHtml(__('Company Roles')) ?>
            </caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('ID')) ?></th>
                <th scope="col" class="col name"><?= $block->escapeHtml(__('Name')) ?></th>
                <th scope="col" class="col name"><?= $block->escapeHtml(__('Users')) ?></th>
                <th scope="col" class="col action"><?= $block->escapeHtml(__('Actions')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var $role \Magento\Customer\Api\Data\CustomerInterface */  ?>
            <?php foreach ($roleList as $role): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                        <?= $block->escapeHtml($role->getId()) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name">
                        <?= $block->escapeHtml($role->getName()) ?>
                        <?php if ($role->isDefault()): ?><?= $block->escapeHtml('(default)') ?> <?php endif; ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Users')) ?>" class="col users">
                        <?= $block->escapeHtml($role->getCountUsers()) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col action">
                        <?= /* @noEscape */ $block->renderButton('aw_ca.role.list.edit', $roleViewModel->getEditUrl($role->getId())) ?>
                        <!-- |
                        <?= /* @noEscape */ $block->renderButton('aw_ca.role.list.delete', $roleViewModel->getDeleteUrl($role->getId())) ?>-->
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <script>
        require([
            'jquery',
            'Magento_Ui/js/modal/confirm'
        ],
        function($, confirmation) {
            $('.confirm_window').on('click', function(event) {
                var self = $(this);
                event.preventDefault();
                confirmation({
                    title: 'Delete this Role?',
                    content: 'Are you sure you want to delete this role?',
                    actions: {
                        /**
                         * Callback confirm.
                         */
                        confirm: function () {
                            window.location.href = self.attr('href');
                        },
                    }
                });
            });
        });
    </script>
    <?php if ($block->getChildHtml('pager')): ?>
        <div class="toolbar bottom"><?= /* @noEscape */ $block->getChildHtml('pager') ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $block->escapeHtml(__('You have created no roles.')) ?></span>
    </div>
<?php endif ?>
