<?php

/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php $themeHelperImage = $this->helper('MGS\ThemeSettings\Helper\Image'); ?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$activeTitle = $themeSettingConfig->getStoreConfig('themesettings/page_title/title_toolbar');
$showFilter = $themeSettingConfig->getStoreConfig('mgs_ajaxnavigation/general/always_show');
$activeBreadcrumb = $themeSettingConfig->getStoreConfig('themesettings/page_title/breadcrumb_category');
$moveBreadcrumb = $themeSettingConfig->getStoreConfig('themesettings/page_title/breadcrumb_toolbar');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$hoverChange = $themeSettingConfig->getStoreConfig('themesettings/catalog/hover_change');
$effect = $themeSettingConfig->getStoreConfig('themesettings/category/product_hover_effect');
$dataHelper = $this->helper('MGS\AjaxCart\Helper\Data');
$lazyLoad = $themeSettingConfig->getStoreConfig('themesettings/general/lazy_load');
$baseImageLazyload = $this->getViewFileUrl($themeSettingConfig->getPathImageLazyLoad());
$isLogged = $this->helper('Aventi\ManagerPrice\Helper\Data')->_getIsLogged();
$_helperStock = $this->helper(Aventi\ExcelModeView\Helper\Stock::class);
$inventoryBlock = $this->getLayout()->createBlock("Aventi\ShowInventory\Block\Product\Inventory");
?>
<!-- Hide Element -->
<?php
$hideReview = $themeSettingConfig->getStoreConfig('themesettings/catalog/review');
$hideAddCart = $themeSettingConfig->getStoreConfig('themesettings/catalog/add_to_cart');
$hideWishlist = $themeSettingConfig->getStoreConfig('themesettings/catalog/wishlist_button');
$hideCompare = $themeSettingConfig->getStoreConfig('themesettings/catalog/compare_button');
$hideHoverMb = $themeSettingConfig->getStoreConfig('themesettings/catalog/hover_effect_mb');


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

?>



<style>
	.product.name{
		height: 40px;
	}
</style>

<?php if (!$_productCollection->count()) : ?>
	<div class="category-product-actions <?php if ($activeTitle) : ?> have-title<?php if (!$activeBreadcrumb && $moveBreadcrumb) : ?> show-breadcrumbs<?php endif ?><?php endif ?>">
		<div class="filter-wrapper">
			<?= $this->getChildHtml('category.title.page'); ?>
		</div>
	</div>
	<div id="current-filter-place">
		<?= $this->getLayout()->createBlock(\Magento\LayeredNavigation\Block\Navigation\State::class)->toHtml(); ?>
	</div>
	<div class="message info empty">
		<div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
	</div>
<?php else : ?>

	<div class="category-product-actions <?php if ($activeTitle) : ?> have-title<?php if (!$activeBreadcrumb && $moveBreadcrumb) : ?> show-breadcrumbs<?php endif ?><?php endif ?><?php if ($showFilter) : ?> always_show<?php endif ?>">
		<div class="filter-wrapper">
			<?= $this->getChildHtml('category.title.page'); ?>

			<?= $block->getToolbarHtml() ?>
		</div>
	</div>

	<?php
	if ($block->getMode() == 'grid') {
		$viewMode = 'grid';
		$image = 'category_page_grid';
		$showDescription = false;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	} else if ($block->getMode() == 'excel') {
		$viewMode = 'excel';
		$image = 'category_page_list';
		$showDescription = false;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
	} else {
		$viewMode = 'list';
		$image = 'category_page_list';
		$showDescription = true;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
	}
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos = $block->getPositioned();
	?>
	<!-- <?php if ($block->getMode() == 'excel') : ?>
		<div class="product-log-product product-log-tab-titles">
			<div class="product-details-container">
				<p class="title">
					Producto
				</p>
			</div>
			<div class="qty-container">
				<p class="title">
					Cantidad
				</p>
			</div>
			<div class="price-container">
				<p class="title">
					Total
				</p>
			</div>
			<div class="actions-container">
				<p class="title">
					Al carrito
				</p>
			</div>
		</div>
	<?php endif ?> -->
	<div class="products wrapper <?php if ($hideHoverMb) : ?> hide-hover-mb <?php endif ?> mgs-products <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?> <?php echo $effect; ?>">
		<?= $block->getAdditionalHtml() ?>
		<?php $iterator = 1; ?>
		<div class="products list items <?php if ($hideWishlist) : ?> hide-wishlist <?php endif ?> product-items">
			<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			<?php foreach ($_productCollection as $_product) : ?>
				<?php $listMaterial = ($_product->getCustomAttribute('list_material')) ? $_product->getCustomAttribute('list_material')->getValue() : 0; ?>
				<?php $productType = $_product->getTypeId(); ?>
				<?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
				<div class="product-item-info  <?php if ($isLogged) :?>login<?php endif; ?> <?php if ($block->getMode() == 'list') : ?> lib-flex <?php endif ?>" data-container="product-grid">
					<?php
					$productImage = $block->getImage($_product, 'category_page_grid');
					if ($pos != null) {
						$position = ' style="left:' . $productImage->getWidth() . 'px;'
							. 'top:' . $productImage->getHeight() . 'px;"';
					}
					$productImageFirst = $productImage = $_imagehelper->init($_product, $image)->getUrl();
					if ($hoverChange) {
						$productImageHoverFirst = $productImageHover = $_imagehelper->init($_product, 'product_base_image')->getUrl();
					}
					?>
					<?php if ($block->getMode() != 'excel') : ?>
						<?php echo $themeSettingConfig->getProductLabel($_product); ?>
					<?php endif ?>
					<?php if ($effect = 'effect2' || $effect = 'effect4') : ?>
						<div class="action-wishlist">
						</div>
					<?php endif ?>
					<?php if ($block->getMode() == 'grid') : ?>
						<?php // Product Image
						?>
						<div class="product-top <?php if ($hideCompare && $hideAddCart) : ?> hide-inner-action-mb  <?php endif ?>">
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
								<span class="product-image-container">
									<span class="<?php if ($lazyLoad): ?>parent_lazy<?php endif; ?> product-image-wrapper" style="padding-bottom: <?php /* @escapeNotVerified */ echo ($themeHelperImage->getRatio() * 100); ?>%;">
										<?php
											if($lazyLoad) {
												$productImageFirst = $baseImageLazyload;
											}
										?>
										<img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid product-image-photo <?php if($lazyLoad): ?>lazy <?php endif; ?> " data-src="<?php echo $productImage ?>" />
										<?php if ($hoverChange) : ?>
											<?php if (basename($_product->getData('base_image')) !=  'no_selection') : ?>
												<?php if (basename($_product->getData('base_image')) != basename($_product->getData('small_image'))) : ?>
													<img src="<?php echo $productImageHoverFirst ?>" alt="<?php echo $imgAlt ?>" class="img-fluid img-hover-show" data-src="<?php echo $productImageHover ?>" />
												<?php endif ?>
											<?php endif ?>
										<?php endif ?>
									</span>
								</span>
							</a>
							<div class="product-item-inner">
								<div class="product actions <?php if ($hideCompare) : ?> hide-compare  <?php endif ?> <?php if ($hideAddCart) : ?> hide-action-cart  <?php endif ?> product-item-actions" <?= strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
					                  <?php if ($isLogged) :?>
					                    <?php if (!$hideAddCart) : ?>
					                      <div class="actions-primary" <?= strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
											<?php if ($_product->isSaleable()) : ?>

					                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
					                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
					                              <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
					                              <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
					                              <?= $block->getBlockHtml('formkey') ?>
					                              <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
					                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
					                              </button>
					                            </form>
					                        <?php else : ?>
					                          <?php if ($_product->getIsSalable()) : ?>
					                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
					                          <?php else : ?>
					                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
					                          <?php endif; ?>
					                        <?php endif; ?>
					                      </div>
										<?php endif; ?>
					                  <?php endif; ?>
									<div data-role="add-to-links" class="actions-secondary " <?= strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
										<?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
											<?= $addToBlock->setProduct($_product)->getChildHtml(); ?>
										<?php endif; ?>
									</div>
								</div>
							</div>
						</div>
						<div class="product details product-item-details">
							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							$cateLink = $themeSettingConfig->getCate($_product);
							?>
							<!--
							<?php if ($cateLink) : ?>
								<div class="product-cate">
									<?php echo $cateLink; ?>
								</div>
							<?php endif ?>
							-->
							<div class="product-brand">
								<a href=""><?php echo $_product->getResource()->getAttribute('mgs_brand')->getFrontend()->getValue($_product); ?></a>
							</div>
							<hr class="product-availability">
							<!--<div class="product-characteristics hover-displayed">

							</div>-->
							<strong class="product name product-item-name">
								<a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</strong>
							<hr class="hover-displayed">
							<div class="product-refs hover-displayed">
							<span class="label-ref">
								<span><strong>SKU</strong></span> <?= $_product->getResource()->getAttribute('ref')->getFrontend()->getValue($_product) ?>
							</span>
							<?php if($_product->getResource()->getAttribute('upc')->getFrontend()->getValue($_product)) : ?>
								<span class="label-upc">
									<strong><?= $_product->getResource()->getAttribute('upc')->getFrontend()->getLabel($_product) ?> : </strong> <?= $_product->getResource()->getAttribute('upc')->getFrontend()->getValue($_product) ?>
								</span>
							<?php endif; ?>
							</div>
							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

							<?php if ($isLogged) : ?>
								<span class="text-price-label hover-displayed no-tax">
									<?php echo __('Price without TAX') ?>
								</span>
								<?php if($listMaterial): ?>
									<div class="content-inventory">
										<?php echo $inventoryBlock->displaySourceInventoryListMaterial($_product->getSku()) ?>
									</div>
								<?php else: ?>
									<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setKey($_product->getSku())->setTemplate("Aventi_ShowInventory::inventory-button.phtml")->toHtml() ?>
								<?php endif; ?>
								<!-- <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setKey($_product->getSku())->setTemplate("Aventi_ShowInventory::inventory-button.phtml")->toHtml() ?> -->
							<?php endif; ?>
							<?php if(!$hideReview): ?>
								<?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
							<?php endif ?>

							<?= $block->getProductDetailsHtml($_product); ?>
							<?php if ($showDescription) : ?>
								<div class="product description product-item-description">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								</div>
							<?php endif; ?>
						</div>
					<?php elseif ($block->getMode() == 'excel') : ?>
						<?php $NotLoggedPlaceholder = '<a href="#" class="not-logged-placeholder">
							<svg width="20" height="22" viewBox="0 0 20 22" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M17 10H3C1.89543 10 1 10.8954 1 12V19C1 20.1046 1.89543 21 3 21H17C18.1046 21 19 20.1046 19 19V12C19 10.8954 18.1046 10 17 10Z" stroke="#9E9E9E" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
								<path d="M5 10V6C5 4.67392 5.52678 3.40215 6.46447 2.46447C7.40215 1.52678 8.67392 1 10 1C11.3261 1 12.5979 1.52678 13.5355 2.46447C14.4732 3.40215 15 4.67392 15 6V10" stroke="#9E9E9E" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
							</svg>
							<div class="floating-container">
								<div class="toltip">Inicia sesión o registrate para continuar</div>
							</div>
						</a>'
						?>

						<div class="product-log-product">
							<div class="label-container">
								<?php if ($block->getMode() == 'excel') : ?>
									<?php echo $themeSettingConfig->getProductLabel($_product); ?>
								<?php endif ?>
							</div>
							<div style="display: flex">
								<div class="product-photo">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
										<span class="product-image-container">
											<span class="<?php if($lazyLoad): ?>parent_lazy<?php endif; ?> product-image-wrapper" style="padding-bottom: <?php /* @escapeNotVerified */ echo ($themeHelperImage->getRatio() * 100); ?>%;">
												<?php
													if($lazyLoad) {
														$productImageFirst = $baseImageLazyload;
													}
												?>
												<img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid product-image-photo <?php if($lazyLoad): ?>lazy <?php endif; ?> " data-src="<?php echo $productImage ?>" />
												<?php if ($hoverChange) : ?>
													<?php if (basename($_product->getData('thumbnail')) !=  'no_selection') : ?>
														<?php if (basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))) : ?>
															<img src="<?php echo $productImageHoverFirst ?>" alt="<?php echo $imgAlt ?>" class="img-fluid img-hover-show <?php if($lazyLoad): ?>lazy <?php endif; ?>" data-src="<?php echo $productImageHover ?>" />
														<?php endif ?>
													<?php endif ?>
												<?php endif ?>
											</span>
										</span>
									</a>
								</div>
								<div class="product-details">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product name product-item-name" tabindex="-1">
										<h4><?php echo $imgAlt ?></h4>
									</a>
									<p class="product-brand">
										<?php echo $_product->getResource()->getAttribute('mgs_brand')->getFrontend()->getValue($_product); ?>
									</p>
									<p class="ids">
										<strong>SKU S21: </strong><?= $_product->getResource()->getAttribute('sku')->getFrontend()->getValue($_product) ?> <br>
										<strong>SKU: </strong><?= $_product->getResource()->getAttribute('ref')->getFrontend()->getValue($_product) ?>
										<?php if($_product->getResource()->getAttribute('upc')->getFrontend()->getValue($_product)) : ?>
											<span class="label-upc">
												<strong><?= $_product->getResource()->getAttribute('upc')->getFrontend()->getLabel($_product) ?> : </strong> <?= $_product->getResource()->getAttribute('upc')->getFrontend()->getValue($_product) ?>
											</span>
										<?php endif; ?>
									</p>
								</div>
							</div>
							<div class="product-buy-container">
								<?php if ($isLogged) :?>


									<div class="action-detail-container">
										<div class="price-container">
											<div class="price-placeholder">
												<div class="price-placeholder__price">
													<span>
														<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
													</span>
												</div>
												<div class="price-tag">
													<span>
														<?php echo __('Price without TAX') ?>
													</span>
												</div>
											</div>
											<div class="price-placeholder">
												<div class="price-placeholder__price total-price-container">
													<div id="total_price_<?= $_product->getId(); ?>" class="price">US$0,00</div>
												</div>
												<div class="price-tag">
													<span>
														<?php echo __('Total price') ?>
													</span>
												</div>
											</div>
										</div>
										<div class="actions-container">
											<div class="qty-container" style="text-align:center">
												<?php if ($isLogged) :?>
													<div class="field qty">
														<div class="qty-pr">
															<!-- <span class="edit-qty minus disable-select-text" onclick="minusQty('<?= $_product->getId(); ?>')"><i class="icon-minus"></i></span> -->
															<input type="number"
																name="qty"
																id="qty_<?= $_product->getId(); ?>"
																min="0"
																value="<?= $block->getProductDefaultQty() * 1 ?>"
																title="<?= __('Qty') ?>" class="input-text qty"
																data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
																onchange="calc('<?= $_product->getId(); ?>');"
																/>
															<!-- <span class="edit-qty plus disable-select-text" onclick="plusQty('<?= $_product->getId(); ?>')"><i class="icon-plus"></i></span> -->
														</div>
													</div>
												<?php else : ?>
													<?php echo $NotLoggedPlaceholder ?>
												<?php endif; ?>
											</div>

											<?php if ($isLogged) :?>
												<?php if (!$hideAddCart) : ?>
													<div class="actions-primary" <?= strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
														<?php if ($_product->isSaleable()) : ?>
															<?php $postParams = $block->getAddToCartPostParams($_product); ?>
															<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
																<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
																<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
																<input type="hidden" id="addto_<?= $_product->getId(); ?>" name="qty" value="">
																<?= $block->getBlockHtml('formkey') ?>
																<button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
																	<span>
																		<i class="icon-shopping-cart"></i>
																	</span>
																</button>
															</form>

															<div class="aw-ctq-button-container">
																<button title="<?php echo __("Add To Quote")?>" type="button" class="secondary toquotelist" >
																	<i class="la la-file-text-o"></i>
																</button>
															</div>
														<?php else : ?>
															<?php if ($_product->getIsSalable()) : ?>
																<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
															<?php else : ?>
																<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>
													</div>
												<?php endif; ?>
											<?php else : ?>
												<?php echo $NotLoggedPlaceholder ?>
											<?php endif; ?>
										</div>

									</div>
										
									<?php if ($isLogged) : ?>
										<div class="inventory-container">
											<?php if($listMaterial): ?>
												<div class="content-inventory">
													<?php echo $inventoryBlock->displaySourceInventoryListMaterial($_product->getSku()) ?>
												</div>
											<?php else: ?>
												<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setKey($_product->getSku())->setTemplate("Aventi_ShowInventory::inventory-button.phtml")->toHtml() ?>
												<?php if($productType == 'simple'): ?>
													<div class="content-inventory">
														<?php echo $inventoryBlock->displaySourceInventoryByCity($_product->getSku()) ?>
													</div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php endif; ?>
								
								<?php else: ?>
									<p class="not-logged-text">
										Inicia sesión para ver precios y realizar compras.
									</p>
								<?php endif; ?>
							</div>
						</div>
						
					<?php else : ?>
						<?php // Product Image
						?>
						<?php // Product List
						?>
						<div class="product-left ">
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
								<span class="product-image-container">
									<span class="<?php if($lazyLoad): ?>parent_lazy <?php endif; ?> product-image-wrapper" style="padding-bottom: <?php /* @escapeNotVerified */ echo ($themeHelperImage->getRatio() * 100); ?>%;">
										<?php
											if($lazyLoad) {
												$productImageFirst = $baseImageLazyload;
											}
										?>
										<img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid product-image-photo <?php if($lazyLoad): ?>lazy <?php endif; ?> " data-src="<?php echo $productImage ?>" />
										<?php if ($hoverChange) : ?>
											<?php if (basename($_product->getData('thumbnail')) !=  'no_selection') : ?>
												<?php if (basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))) : ?>
													<img src="<?php echo $productImageHoverFirst ?>" alt="<?php echo $imgAlt ?>" class="img-fluid img-hover-show <?php if($lazyLoad): ?>lazy <?php endif; ?>" data-src="<?php echo $productImageHover ?>" />
												<?php endif ?>
											<?php endif ?>
										<?php endif ?>
									</span>
								</span>
							</a>
						</div>
						<div class="product-right details product-item-details">
							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							$cateLink = $themeSettingConfig->getCate($_product);
							?>
							<!--
								<?php if ($cateLink) : ?>
									<div class="product-cate">
										<?php echo $cateLink; ?>
									</div>
								<?php endif ?>
							-->

							<div class="product-brand">
								<a href=""><?php echo $_product->getResource()->getAttribute('mgs_brand')->getFrontend()->getValue($_product); ?></a>
							</div>
							<hr class="product-availability">
							<strong class="product name product-item-name">
								<a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</strong>
							<div class="product-refs">
								<span><strong>SKU 21</strong></span>: <?= $_product->getResource()->getAttribute('sku')->getFrontend()->getValue($_product) ?>
								<br>
								<span><strong>SKU</strong></span>: <?= $_product->getResource()->getAttribute('ref')->getFrontend()->getValue($_product) ?>
								<?php if($_product->getResource()->getAttribute('upc')->getFrontend()->getValue($_product)) : ?>
									<span class="label-upc">
										<strong><?= $_product->getResource()->getAttribute('upc')->getFrontend()->getLabel($_product) ?> : </strong> <?= $_product->getResource()->getAttribute('upc')->getFrontend()->getValue($_product) ?>
									</span>
								<?php endif; ?>

							</div>
							<!--
								<?php if ($showDescription) : ?>
									<div class="product description product-item-description">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									</div>
								<?php endif; ?>
							-->

							<?= $block->getProductDetailsHtml($_product); ?>

							<div class="product-item-inner">
								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								<?php if ($isLogged) : ?>
									<span class="text-price-label">
										<?php echo __('Price without TAX') ?>
									</span>
								<?php endif; ?>
								<?php if (!$hideReview) : ?>
									<?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<?php endif ?>
								<div class="product actions product-item-actions" <?= strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<div class="actions-primary" <?= strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
										<?php if ($isLogged) : ?>
											<?php if ($_product->isSaleable()) : ?>
												<?php if (!$hideAddCart) : ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?= $block->getBlockHtml('formkey') ?>
														<button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php endif ?>
											<?php else : ?>
												<?php if ($_product->getIsSalable()) : ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else : ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									<div data-role="add-to-links" class="actions-secondary" <?= strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
										<?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
											<?= $addToBlock->setProduct($_product)->getChildHtml(); ?>
										<?php endif; ?>
									</div>
									<?php if ($isLogged) : ?>
										<div class="inventory-container">
											<?php if($listMaterial): ?>
												<div class="content-inventory">
													<?php echo $inventoryBlock->displaySourceInventoryListMaterial($_product->getSku()) ?>
												</div>
											<?php else: ?>
												<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setKey($_product->getSku())->setTemplate("Aventi_ShowInventory::inventory-button.phtml")->toHtml() ?>
												<?php if($productType == 'simple'): ?>
													<div class="content-inventory">
														<?php echo $inventoryBlock->displaySourceInventoryByCity($_product->getSku()) ?>
													</div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php endif; ?>
								</div>
							</div>
						</div>
					<?php endif; ?>
				</div>
				<?= ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
			<?php endforeach; ?>
		</div>
		<div class="bottom-toolbar">
			<?= $block->getToolbarHtml() ?>
		</div>
	</div>

	<?php if (!$block->isRedirectToCartEnabled()) : ?>
		<script type="text/x-magento-init">
			{
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
	<?php endif; ?>
<?php endif; ?>


<script type="text/javascript">
	require([
		'jquery'
	], function(jQuery) {
		(function($) {
			$('.action-filter').click(function() {
				$(this).toggleClass('active');
				$('body.page-with-filter').toggleClass('open-filter');
			});
			<?php if ($effect = 'effect2' || $effect = 'effect4' || $effect = 'effect8') : ?>
				$(document).ready(function() {
					$(".products-grid.effect2 .product-items .product-item .product-item-info, .products-grid.effect4 .product-items .product-item .product-item-info, .products-grid.effect8 .product-items .product-item .product-item-info ").each(function() {
						$(this).find(' .product-item-inner > .product-item-actions > .actions-secondary > .action.towishlist').appendTo($(this).find('.action-wishlist'));
					});
				});
			<?php endif ?>

		})(jQuery);


	});
</script>

<script type="text/javascript">

	function plusQty(qtyInput){
		require([
		'jquery'
		], function($){
			if($('#qty_'+qtyInput).attr('disabled')!='disabled'){
				//total = 0;
				qty = $('#qty_'+qtyInput).attr('value');
				price = $('#product-price-'+qtyInput).attr('data-price-amount');
				qty = parseInt(qty);
				price = parseFloat(price);
				qty++;
				price = price * qty;
				$('#qty_'+qtyInput).val(qty);
				$('#total_price_'+qtyInput).text('$'+price.toFixed(2));
				$('#addto_'+qtyInput).val(qty);
				$('#sticky_qty').val(qty);
			}
		});

	}
	function minusQty(qtyInput){
		require([
		'jquery'
		], function($){
			if($('#qty_'+qtyInput).attr('disabled')!='disabled'){
				qty = $('#qty_'+qtyInput).attr('value');
				qty = parseInt(qty);
				price = $('#product-price-'+qtyInput).attr('data-price-amount');
				price = parseFloat(price);
				qty--;
				price = price * qty;
				if(qty >= 0){
					$('#qty_'+qtyInput).val(qty);
					$('#total_price_'+qtyInput).text('$'+price.toFixed(2));
					$('#addto_'+qtyInput).val(qty);
					$('#sticky_qty').val(qty);
				}
			}
		});
	}
	function calc(qtyInput){
		require([
		'jquery'
		], function($){
			if($('#qty_'+qtyInput).attr('disabled')!='disabled'){
				qty = $('#qty_'+qtyInput).attr('value');
				qty = parseInt(qty);
				price = $('#product-price-'+qtyInput).attr('data-price-amount');
				price = parseFloat(price)
				price = price * qty;
				$('#total_price_'+qtyInput).text('$'+price.toFixed(2));
				$('#addto_'+qtyInput).val(qty);
				$('#sticky_qty').val(qty);
			}
		});
	}
</script>
