<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $helper = $this->helper('MGS\Protabs\Helper\Data') ?>
<?php $themeHelper = $this->helper('MGS\ThemeSettings\Helper\Config'); ?>
<?php $glrTemplate = $themeHelper->getStoreConfig('extragallery/general/glr_type'); ?>

<?php $tabCollection = $helper->getTabsCollection() ?>
<?php if($tabCollection->getSize()): ?>
	<?php if($helper->getStoreConfig('protabs/general/type')): ?>
		<div class="product-detail-infomation margin-top65">
	<?php endif ?>
	<div class="product info detailed <?php if($themeHelper->getStoreConfig('protabs/general/extended')): ?>extended<?php endif ?> <?php if((!$helper->getStoreConfig('protabs/general/position')) || ($glrTemplate == 3) ): ?>after-content<?php endif ?> <?php if($helper->getStoreConfig('protabs/general/type')): ?>accordion<?php endif ?> ">

		<?php $layout = $block->getLayout(); ?>
		<div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
			<div class="product-data-items-menu">
				<?php foreach($tabCollection as $_tab): ?>
					
					<?php if(($_tab->getTabType() == 'attribute') || ($_tab->getTabType() == 'static')): ?>
						<?php if(trim($_tab->getValue()) !=''): ?>
							<?php if($_tab->getTabType() == 'attribute'): ?>
								<?php 
									$html = $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View\Description')
									->setAtCall($helper->convertAttributeToCallName($_tab->getValue()))
									->setAtCode($_tab->getValue())
									->setCssClass('description')
									->setAtLabel('none')
									->setAtType($helper->getAttributeType($_tab->getValue()))
									->setTitle($_tab->getTitle())
									->setTemplate('MGS_Protabs::product/view/attribute.phtml')
									->toHtml() 
								?>
							<?php else: ?>
								<?php $html = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($_tab->getValue())->toHtml() ?>
							<?php endif ?>
							
							<?php 
								if (!trim($html)) {
									continue;
								}
								$alias = $_tab->getTabType().$_tab->getValue();
								$label = $_tab->getTitle();
							?>
							
							<div class="data item title"
								 aria-labeledby="tab-label-<?php echo $alias;?>-title"
								 data-role="collapsible" id="tab-label-<?php echo $alias;?>">
								<a class="data switch"
								   tabindex="-1"
								   data-toggle="switch"
								   href="#<?php echo $alias; ?>"
								   id="tab-label-<?php echo $alias;?>-title">
									<?php echo $label; ?>
								</a>
							</div>
							
							
						<?php endif ?>
					<?php else: ?>
						<?php 
							$html = $layout->renderElement($_tab->getTabType());
							if (!trim($html)) {
								continue;
							}
							$alias = $layout->getElementAlias($_tab->getTabType());
							
							$label = $_tab->getTitle();
							
							
							if($alias == 'reviews'){
								$oldLabel = $block->getChildData($alias, 'title');
								if(is_object($oldLabel)){
									$labelObject = (array)$oldLabel;
									$countArray = end($labelObject);
									if(isset($countArray[0])){
										$label = $label.' '.$countArray[0].'';
									}
								}
							}
						?>
						<div class="data item title"
							 aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
							 data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
							<a class="data switch"
							   tabindex="-1"
							   data-toggle="switch"
							   href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
							   id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
								<?php /* @escapeNotVerified */ echo $label; ?>
							</a>
						</div>
					<?php endif ?>
				<?php endforeach ?>
			</div>
			<div class="product-data-items-content">

				<?php $dn = 0; foreach($tabCollection as $_tab): $dn++; ?>
					<?php if(($_tab->getTabType() == 'attribute') || ($_tab->getTabType() == 'static')): ?>
						<?php if(trim($_tab->getValue()) !=''):?>
							<?php if($_tab->getTabType() == 'attribute'): ?>
								<?php 
									$html = $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View\Description')
									->setAtCall($helper->convertAttributeToCallName($_tab->getValue()))
									->setAtCode($_tab->getValue())
									->setCssClass('description')
									->setAtLabel('none')
									->setAtType($helper->getAttributeType($_tab->getValue()))
									->setTitle($_tab->getTitle())
									->setTemplate('MGS_Protabs::product/view/attribute.phtml')
									->toHtml() 
								?>
							<?php else: ?>
								<?php $html = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($_tab->getValue())->toHtml() ?>
							<?php endif ?>
							
							

							<?php 
								if (!trim($html)) {
									continue;
								}
								$alias = $_tab->getTabType().$_tab->getValue();
								$label = $_tab->getTitle();
							?>
							<div class="title-accordion <?php if($dn == 1): ?> echo active <?php endif ?> accordion-<?php echo $alias;?>" data-toggle="#<?php /* @escapeNotVerified */ echo $alias; ?>"><span><?php /* @escapeNotVerified */ echo $label; ?><span></div>
							<div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
							
							
				                <div>
				                  <?php echo $this->helper('Aventi\Webscrapping\Helper\Information')->getDescrition(); ?>
								  
				                </div>
								<?php /* @escapeNotVerified */ echo $html; ?>
							</div>
							
						<?php endif ?>
					<?php else:?>
						<?php 
							$html = $layout->renderElement($_tab->getTabType());
							if (!trim($html)) {
								continue;
							}
							$alias = $layout->getElementAlias($_tab->getTabType());
							
							$label = $_tab->getTitle();
							
							
							if($alias == 'reviews'){

								$oldLabel = $block->getChildData($alias, 'title');
								if(is_object($oldLabel)){
									$labelObject = (array)$oldLabel;
									$countArray = end($labelObject);
									if(isset($countArray[0])){
										$label = $label.' '.$countArray[0].'';
									}
								}
							}
						?>
						<div class="title-accordion <?php if($dn == 1): ?> echo active <?php endif ?> accordion-<?php echo $alias;?>" data-toggle="#<?php echo $alias; ?>"><span><?php echo $label; ?><span></div>
						<div class="data item content" id="<?php echo $alias; ?>" data-role="content"><?php echo $html; ?></div>
					<?php endif ?>

				<?php endforeach ?>

			</div>
		</div>
	</div>
	<script type="text/javascript">
		require([
			'jquery'
		], function ($) {
			$(document).ready(function(){
				
				$('.title-accordion').click(function(){

	                var itemShow = $(this).data('toggle');
	                if($(this).hasClass('active')){
	                    $(itemShow).slideUp();
	                    $(this).removeClass('active');
	                }else {
	                    $('.product-data-items-content .title-accordion.active').removeClass('active');
	                    $(".product-data-items-content .data.item.content").slideUp();
	                    $(itemShow).slideDown();
	                    $(this).addClass('active');
	                }
				});
			});
		});
	</script>
	<?php if($helper->getStoreConfig('protabs/general/type')): ?>
		</div>
	<?php endif ?>
<?php endif ?>
