<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /* @var $block \MageWorx\AlsoBought\Block\System\Config\Collect */ ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var collectSpan = jQuery('#collect_span');

        jQuery('#collect_button').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    jQuery('#collect_message_span').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        collectSpan.find('.collected').show();
                    }
                    jQuery('#collect_message_span').text(resultText);

                    var json = response.responseJSON;                                     
                    if (json.result != null) {                        
                                                
                        var html = `<tr><td>${json.result.total}</td><td>${json.result.completed}</td><td>${json.result.noFound}</td><td>${json.result.NoProcessing}</td></tr>`;                                    
                        console.log(html);
                        jQuery('#result-table').find('tbody').append(html);                        
                        jQuery('#result-table').show();
                    }                                  
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="collect_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="collect_message_span"></span>
</span>
<table class="table" style="border:1px solid #000;margin:5px;text-align:center;" id="result-table"  hidden="hidden">
    <thead>
        <tr>
            <th>Total</th>
            <th>Completed</th>
            <th>No Found</th>
            <th>No Proccessing</th>
        </tr>        
    </thead>
    <tbody>        
    </tbody>
</table>