<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="product">
	<div class="product-media">
		<a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" title="<?php echo $block->escapeHtml($product->getName()) ?>">
		    <?php echo $block->getImage($product, 'wishlist_thumbnail')->toHtml(); ?>
		</a>
	</div>
	<h3 class="product-item-name">
	    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" title="<?php echo $block->escapeHtml($product->getName()) ?>" class="product-item-link">
	        <?php echo $block->escapeHtml($product->getName()) ?>
	    </a>
	</h3>
</div>
