<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Account Information') ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <span class="color-info"><?= __('Name:')?>&nbsp;</span><?= $block->escapeHtml($block->getName()) ?><br/>
                    <span class="color-info"><?= __('Email:')?>&nbsp;</span><?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br/>
                </p>
            </div>
            <div class="box-actions">
                <a class="action edit edit-billding btn btn-default btn-rounded icon-right" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/edit') ?>">
                    <?php /* @escapeNotVerified */ echo __('Edit your account information') ?>
                </a>
            </div>
        </div>
        <div class="box box-information">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Roles and Permissions') ?></span>
            </strong>

            <div class="box-actions">
                <a class="action edit edit-billding btn btn-default btn-rounded icon-right" href="<?php /* @escapeNotVerified */ echo $block->getUrl('aw_ca/role/') ?>">
                    <?php /* @escapeNotVerified */ echo __('Editar roles y usuarios') ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Newsletters') ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?php /* @escapeNotVerified */ echo __('You subscribe to "General Subscription".') ?>
                        <?php else: ?>
                            <?php /* @escapeNotVerified */ echo __('You don\'t subscribe to our newsletter.') ?>
                        <?php endif; ?>
                    </p>
                    <?php /* Extensions placeholder */ ?>
                    <?= $block->getChildHtml('customer.account.dashboard.info.extra')?>
                </div>
                <div class="box-actions">
                    <a class="action edit btn btn-default btn-rounded icon-right" href="<?php /* @escapeNotVerified */ echo $block->getUrl('newsletter/manage') ?>"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
