<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Aventi\SAP\Block\Invoice\History $block */
?>
<?php $_invoices = $block->getInvoices(); ?>
<?php if ($_invoices && count($_invoices)) : ?>

    <div class="table-wrapper invoices-history">
        <table class="data table table-invoice-items history" id="my-invoices-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Invoices')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Invoice #')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <th scope="col" class="col total"><?= $block->escapeHtml(__('Invoice Total')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_invoices as $_invoice) : ?>
                <tr>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Invoice #')) ?>" class="col id"><?= $block->escapeHtml($_invoice['DocNum']) ?></td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_invoice['DocDate']) ?></td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Invoice Total')) ?>" class="col total"><?= /* @noEscape */ $_invoice['DocTotal'] ?></td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_invoice['DocStatus']) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="scroll-indicator">
        <svg width="24" height="22" viewBox="0 0 24 22" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M10.9393 21.0607C11.5251 21.6464 12.4749 21.6464 13.0607 21.0607L22.6066 11.5147C23.1924 10.9289 23.1924 9.97919 22.6066 9.3934C22.0208 8.80761 21.0711 8.80761 20.4853 9.3934L12 17.8787L3.51472 9.3934C2.92893 8.80761 1.97918 8.80761 1.3934 9.3934C0.807611 9.97918 0.807611 10.9289 1.3934 11.5147L10.9393 21.0607ZM10.5 -6.55671e-08L10.5 20L13.5 20L13.5 6.55671e-08L10.5 -6.55671e-08Z" fill="#828282"/>
        </svg>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no invoices.')) ?></span></div>
<?php endif ?>
