<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Ctq\Block\Adminhtml\Quote\Edit\NegotiationTabs\Comment */

// @codingStandardsIgnoreFile
$quoteId = $block->getDataProviderViewModel()->getQuoteId();
?>
<div class="aw-ctq__comments_wrapper">
    <ul class="comments ">
        <?php /** @var  \Aheadworks\Ctq\Api\Data\CommentInterface $comment */ ?>
        <?php foreach ($block->getCommentListViewModel()->getCommentList($quoteId) as $comment): ?>
            <li class="<?= /* @noEscape */ $block->getCommentViewModel()->getCommentClasses($comment) ?>">
                <div class="aw-ctq__owner-name">
                    <span class="aw-ctq__owner-name-value"><?= $block->escapeHtml($block->getCommentViewModel()->getOwnerName($comment)) ?></span>
                    <span class="aw-ctq__date-created-value"><?= /* @noEscape */ $block->getCommentViewModel()->getCreatedAtFormatted($comment->getCreatedAt()) ?></span>
                </div>
                <div class="comment-text"><?= $block->escapeHtml($comment->getComment()) ?></div>
                <?php if ($comment->getAttachments()): ?>
                    <?php foreach ($comment->getAttachments() as $attachment): ?>
                        <div class="attachments">
                            <a target="_blank"
                               href="<?= $block->escapeUrl(
                                       $block->getCommentViewModel()->getDownloadUrl($attachment->getFileName(), $quoteId, $comment->getId())
                               ) ?>">
                                <?= $block->escapeHtml($attachment->getName()) ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>