<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Ctq\Block\Adminhtml\Quote\Edit\NegotiationTabs\History */

// @codingStandardsIgnoreFile
$quoteId = $block->getQuoteId();
?>
<?php if ($quoteId): ?>
<div class="aw-ctq__history-block">
    <ul>
        <?php foreach ($block->getHistoryListViewModel()->getHistorySearchResults($quoteId)->getItems() as $history): ?>
            <li>
                <?= /* @noEscape */ $block->getHistoryItemHtml($history) ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php else: ?>
    <?= $block->escapeHtml(__('History log is not available at the moment.')) ?>
<?php endif ?>