<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

?>

<div class="contact-form">
    <form class="form contact mb-3"
          action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
          data-mage-init='{"validation":{}}'>
        <div class="fieldset">
            <div class="frame">
                <div class="line">
                    <div class="col-des-6 col-tb-6 col-mb-12 input-name">
                        <div class="field name required">
                            <div class="control">
                                <input placeholder="Nombre *" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-des-6 col-tb-6 col-mb-12 input-email">
                        <div class="field email required">
                            <div class="control">
                                <input placeholder="Correo *" name="email" id="contact-email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="line block-comment">
                    <div class="field comment required">

                        <div class="control">
                            <textarea placeholder="Message *" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                        </div>
                    </div>
                    <?= $block->getChildHtml('form.additional.info'); ?>
                    <label class="label note" for="note"><span><?php /* @escapeNotVerified */ echo __('All fields marked * are required') ?>
                </div>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button class="btn btn-default icon-right" type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Message') ?>" class="action submit primary">
                    <?php /* @escapeNotVerified */ echo __('SUBMIT') ?>
                </button>
            </div>
        </div>
    </form>
</div>
           