<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

?>

<style>
#map {
    height: 100%;
    min-height: 400px;
}
</style>
<div class="section-builder contact_form_1">
    <div class="frame no-padding">
        <div class="line">
            <div class="col-des-6 col-tb-12 col-mb-12 mb-2">
                         <div id="alejar"  class="control" >
                            <button id="alejarbu" style="width: 45px;height: 45px; border: none;border-radius: 14px;" title="Restaurar">
                                <i class="fa fa-crosshairs" style="font-size: 20px;"></i></button>
                          </div>
                      
                        <div id="map"></div>
            </div>
            <div class="col-des-6 col-tb-12 col-mb-12 ">
                <h2 class="title mb-1"><?php /* @escapeNotVerified */ echo __('Got Any Questions?') ?></h2>
                <p class="mb-2"><?php /* @escapeNotVerified */ echo __('Use the form below to get in touch with the sales team') ?></p>
                <div class="contact-form">
                    <form class="form contact mb-3"
                          action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
                          id="contact-form"
                          method="post"
                          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
                          data-mage-init='{"validation":{}}'>
                        <div class="fieldset">
                            <div class="frame">
                                <div class="line">
                                    <div class="col-des-6 col-tb-6 col-mb-12 input-name">
                                        <div class="field name required">
                                            <div class="control">
                                                <input placeholder="<?php /* @escapeNotVerified */ echo __('Name *') ?>" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-des-6 col-tb-6 col-mb-12 input-email">
                                        <div class="field email required">
                                            <div class="control">
                                                <input placeholder="<?php /* @escapeNotVerified */ echo __('Email *') ?>" name="email" id="contact-email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="line block-comment">
                                    <div class="field comment required">

                                        <div class="control">
                                            <textarea placeholder="<?php /* @escapeNotVerified */ echo __('Message *') ?>" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                                        </div>
                                    </div>
                                    <?= $block->getChildHtml('form.additional.info'); ?>
                                    <label class="label note" for="note"><span><?php /* @escapeNotVerified */ echo __('All fields marked * are required') ?>
                                </div>
                            </div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <input type="hidden" name="hideit" id="hideit" value="" />
                                <button class="btn btn-default icon-right" type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Message') ?>" class="action submit primary">
                                    <?php /* @escapeNotVerified */ echo __('SUBMIT') ?>
                                </button>
                            </div>
                        </div>
                    </form>
                    <div class="contact-information">
                        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_us_information_block')->toHtml(); ?>
                    </div>
                </div>
                <div class="contact-store">
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_store_block')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="frame no-padding">
        <hr class="mt-4 mb-5">
        <div class="line">
            <?php echo $this->getLayout()->createBlock("MGS\StoreLocator\Block\Stores")->setTemplate("MGS_StoreLocator::storelocator_contact.phtml")->toHtml(); ?>
        </div>
    </div>
</div>
<script>
    		
                function initMap() {
                const options = {
                    mapTypeControl: true,
                    gestureHandling: 'greedy',
                    mapTypeControlOptions: {
                            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,        
                    }
                }

        var arreglopos =[new google.maps.LatLng(-2.1437714, -79.8869125), 
                        new google.maps.LatLng(-0.1592637, -78.4923232)];
        
        
        var arreglodatos =[
                {           "direccion" : "Av. Isidro Ayora Cdla. La Garzota Mz.138 S.20",
                             "telefono" :  "04 3732121",
                             "sitio" : "soporteonline@siglo21.net"},            
                            {"direccion" : "Calle El Condor Oe5-32 Y Av. Edmundo Carvajal",
                             "telefono" :  "02 3732121",
                             "sitio" : "soporteonline@siglo21.net"}
        ];
                            
        var mapa = new google.maps.Map(document.getElementById('map'), options);
        mapa.setTilt(45);

        var bounds = new google.maps.LatLngBounds();
        var centrado_del_mapa=bounds;
  

        for(var i=0; i<arreglopos.length; i++){
            position = arreglopos[i];
            bounds.extend(position);
        }

        mapa.fitBounds(bounds);




///////////////////////////////////////////////////////////
function smoothZoom (map, max, cnt) {
    if (cnt >= max) {
        return;
    }
    else {
        z = google.maps.event.addListener(mapa, 'zoom_changed', function(event){
            google.maps.event.removeListener(z);
            smoothZoom(map, max, cnt + 1);
        });
        setTimeout(function(){map.setZoom(cnt)}, 80); 
    }

}
//////////////////////////////////////////////////////////




        var markers = arreglopos.map(function(location, j) {        
        var maker = new google.maps.Marker({
            position: location,
            map: mapa
          });

            var contentString2 = '<div><b> Direccion:&nbsp</b>'+arreglodatos[j]['direccion']+'</div>'+
                                 '<div><b> Telefono:&nbsp</b>'+arreglodatos[j]['telefono']+'</div>'+
                                 '<div class="mapas"><b> Sitio:&nbsp</b><a href="mailto:'+arreglodatos[j]['sitio']+'" >'+arreglodatos[j]['sitio']+'</div>';

            var infowindow = new google.maps.InfoWindow({
                  content: contentString2
                });

          maker.addListener('zoom_changed', function(){
            infowindow.open(mapa,maker);

          });

        maker.addListener('dblclick', function(){
            infowindow.open(mapa,maker);
            mapa.setCenter(maker.getPosition());
            smoothZoom(mapa, 17, mapa.getZoom());
          });


        maker.addListener('click', function(){
            infowindow.open(mapa,maker);
          });




           return maker;
          
        });


        var alejar = document.getElementById('alejar');
        mapa.controls[google.maps.ControlPosition.TOP_RIGHT].push(alejar);
        var alejarbu  = document.getElementById('alejarbu');
        alejarbu.addEventListener('click', function() {
         mapa.fitBounds(centrado_del_mapa);  
        });


    }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCf2qPa7TVm_sbbUPFu1VU5qyfR_iCpezY&callback=initMap"></script>

