<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** $block \Aheadworks\Ctq\Block\Adminhtml\Quote\Edit\QuotedItems\Grid */
?>
<?php
$_items = $block->getItems();
$quote = $block->getQuote();
/** @var \Aheadworks\Ctq\Model\Quote\Admin\Quote\Total\Calculator $calculator */
$calculator = $block->getTotalCalculator();
?>
<?php if (empty($_items)): ?>
    <div id="quote-items_grid">
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary order-tables">
                <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                        <th class="col-cost"><span><?= /* @escapeNotVerified */ __('Cost') ?></span></th>
                        <th class="col-catalog-price"><span><?= /* @escapeNotVerified */ __('Catalog Price') ?></span></th>
                        <th class="col-cart-price"><span><?= /* @escapeNotVerified */ __('Cart Price') ?></span></th>
                        <th class="col-stock"><span><?= /* @escapeNotVerified */ __('Stock') ?></span></th>
                        <th class="col-proposed-price"><span><?= /* @escapeNotVerified */ __('Proposed Price') ?></span></th>
                        <th class="col-qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                        <th class="col-subtotal"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                        <th class="col-negotiated-discount"><span><?= /* @escapeNotVerified */ __('Negotiated Discount') ?></span></th>
                        <th class="col-estimated-tax"><span><?= /* @escapeNotVerified */ __('Estimated Tax') ?></span></th>
                        <th class="col-row-total"><span><?= /* @escapeNotVerified */ __('Row Subtotal') ?></span></th>
                        <th class="col-action"><span><?= /* @escapeNotVerified */ __('Action') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="even">
                        <td class="empty-text" colspan="100"><?= /* @escapeNotVerified */ __('No ordered items') ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php else: ?>
    <div class="admin__table-wrapper" id="quote-items_grid">
    <?php if (count($_items)>10): ?>
        <?php if ($block->getQuoteViewModel()->isEditQuote($block->getQuoteId())):?>
            <div class="actions update actions-update">
                <?= $block->getButtonHtml(__('Update Items and Quantities'), 'quote.itemsUpdate()', 'action-secondary') ?>
            </div>
        <?php endif;?>
    <?php endif; ?>
        <table class="data-table admin__table-primary order-tables">
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                    <th class="col-cost"><span><?= /* @escapeNotVerified */ __('Cost') ?></span></th>
                    <th class="col-catalog-price"><span><?= /* @escapeNotVerified */ __('Catalog Price') ?></span></th>
                    <th class="col-cart-price"><span><?= /* @escapeNotVerified */ __('Cart Price') ?></span></th>
                    <th class="col-proposed-price"><span><?= /* @escapeNotVerified */ __('Proposed Price') ?></span></th>
                    <th class="col-stock"><span><?= /* @escapeNotVerified */ __('Stock') ?></span></th>
                    <th class="col-qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                    <th class="col-subtotal"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                    <th class="col-negotiated-discount"><span><?= /* @escapeNotVerified */ __('Negotiated Discount') ?></span></th>
                    <th class="col-estimated-tax"><span><?= /* @escapeNotVerified */ __('Estimated Tax') ?></span></th>
                    <th class="col-row-total"><span><?= /* @escapeNotVerified */ __('Row Subtotal') ?></span></th>
                    <th class="col-action"><span><?= /* @escapeNotVerified */ __('Action') ?></span></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td class="col-total"><?= /* @escapeNotVerified */ __('Total %1 product(s)', count($_items)) ?></td>
                    <td colspan="6" class="col-subtotal"><?= /* @escapeNotVerified */ __('Subtotal:') ?></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($calculator->getSubtotal($quote)) ?></strong></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($calculator->getNegotiatedDiscountAmount($quote)) ?></strong></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($calculator->getEstimatedTaxTotal($quote)) ?></strong></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($calculator->calculateSubtotalInclDiscountAndTax($quote)) ?></strong></td>
                    <td colspan="2">&nbsp;</td>
                </tr>
            </tfoot>
                <?php $i = 0 ?>
                <?php foreach ($_items as $_item):$i++ ?>
                <tbody class="<?= /* @escapeNotVerified */ ($i%2) ? 'even' : 'odd' ?>">
                    <tr>
                        <td class="col-product">
                            <a target="_blank" href="<?= $block->escapeUrl($block->getLinkToProductEditPage($_item)) ?>">
                                <span id="quote_item_<?= /* @escapeNotVerified */ $_item->getId() ?>_title"><?= $block->escapeHtml($_item->getName()) ?></span>
                            </a>
                            <div class="product-sku-block">
                                <span><?= /* @escapeNotVerified */ __('SKU') ?>:</span>
                                <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))) ?>
                            </div>
                            <?php if ($block->getQuoteViewModel()->isEditQuote($block->getQuoteId())):?>
                                <div class="product-configure-block">
                                    <?= $block->getConfigureButtonHtml($_item) ?>
                                </div>
                            <?php endif;?>
                        </td>
                        <td class="col-cost">
                            <?= /* @escapeNotVerified */ $block->formatPrice($calculator->calculateItemCost($_item)) ?>
                        </td>
                        <td class="col-catalog-price">
                            <?= /* @escapeNotVerified */ $block->formatPrice($_item->getCalculationPrice()) ?>

                            <?php $_isCustomPrice = $block->usedCustomPriceForItem($_item) ?>
                            <?php if ($_tier = $block->getTierHtml($_item)): ?>
                                <div id="item_tier_block_<?= /* @escapeNotVerified */ $_item->getId() ?>"<?php if ($_isCustomPrice): ?> style="display:none"<?php endif; ?>>
                                    <a href="#" onclick="$('item_tier_<?= /* @escapeNotVerified */ $_item->getId() ?>').toggle();return false;"><?= /* @escapeNotVerified */ __('Tier Pricing') ?></a>
                                    <div style="display:none" id="item_tier_<?= /* @escapeNotVerified */ $_item->getId() ?>"><?= /* @escapeNotVerified */ $_tier ?></div>
                                </div>
                            <?php endif; ?>

                            <?php $_isCustomPrice = $block->usedCustomPriceForItem($_item) ?>
                            <?php if ($block->canApplyCustomPrice($_item)): ?>
                                <div class="custom-price-block">
                                    <input type="checkbox"
                                           class="admin__control-checkbox"
                                           id="item_use_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                        <?php if ($_isCustomPrice): ?> checked="checked"<?php endif; ?>
                                           onclick="quote.toggleCustomPrice(this, 'item_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>', 'item_tier_block_<?= /* @escapeNotVerified */ $_item->getId() ?>');"/>
                                    <label
                                            class="normal admin__field-label"
                                            for="item_use_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>">
                                        <span><?= /* @escapeNotVerified */ __('Custom Price') ?>*</span></label>
                                </div>
                            <?php endif; ?>
                            <input id="item_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                   name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][custom_price]"
                                   value="<?= /* @escapeNotVerified */ sprintf("%.2f", $block->getOriginalEditablePrice($_item)) ?>"
                                <?php if (!$_isCustomPrice): ?>
                                   style="display:none"
                                   disabled="disabled"
                                <?php endif; ?>
                                   class="input-text item-price admin__control-text"
                            />
                        </td>
                        <td class="col-cart-price">
                            <?= /* @escapeNotVerified */ $block->formatPrice($calculator->calculateItemCartPrice($_item)) ?>
                        </td>
                        <td class="col-proposed-price">
                            <div class="admin__control-addon">
                                <input name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][proposed_price]"
                                       class="input-text item-price admin__control-text"
                                       value="<?= /* @escapeNotVerified */ $block->getRoundedPrice($calculator->calculateItemProposedPrice($_item)) ?>"
                                       <?= !$block->getQuoteViewModel()->isEditQuote($block->getQuoteId()) ? 'disabled="true"' : '' ?>
                                       maxlength="12" />
                                <label class="admin__addon-prefix"><?= $block->escapeHtmlAttr($block->getCurrencySymbol($quote)) ?></label>
                            </div>
                        </td>
                        <td class="col-stock">
                            <div class="item-stock">
                                <?= /* @escapeNotVerified */ $block->getStockCount($_item) ?>
                            </div>
                        </td>
                        <td class="col-qty">
                            <input name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                                   class="input-text item-qty admin__control-text"
                                   value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                                   <?= !$block->getQuoteViewModel()->isEditQuote($block->getQuoteId()) ? 'disabled="true"' : '' ?>
                                   maxlength="12" />
                        </td>
                        <td class="col-subtotal col-price">
                            <?= /* @escapeNotVerified */ $block->formatPrice($_item->getRowTotal()) ?>
                        </td>
                        <td class="col-negotiated-discount">
                            <?= /* @escapeNotVerified */ $block->formatPrice(-$calculator->calculateItemNegotiatedDiscount($_item)) ?>
                        </td>
                        <td class="col-price col-estimated-tax">
                            <?= /* @escapeNotVerified */ $block->formatPrice($_item->getTaxAmount()) ?>
                        </td>
                        <td class="col-price col-row-total">
                            <?= /* @escapeNotVerified */ $block->formatPrice($calculator->calculateItemRowSubtotal($_item)) ?>
                        </td>
                        <td class="col-actions last">
                            <select class="admin__control-select" name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][action]"
                                <?= !$block->getQuoteViewModel()->isEditQuote($block->getQuoteId()) ? 'disabled="true"' : '' ?>>
                                <option value=""><?= /* @escapeNotVerified */ __('Please select') ?></option>
                                <option value="remove"><?= /* @escapeNotVerified */ __('Remove') ?></option>
                            </select>
                        </td>
                    </tr>

                    <?php $hasMessageError = false; ?>
                    <?php foreach ($_item->getMessage(false) as $messageError):?>
                        <?php if (!empty($messageError)) {
                            $hasMessageError = true;
                        }
                        ?>
                    <?php endforeach; ?>

                    <?php if ($hasMessageError):?>
                        <tr class="row-messages-error">
                            <td colspan="100"> <!-- ToDo UI: remove the 100 -->
                                <?php foreach ($_item->getMessage(false) as $message):
                                    if (empty($message)) {
                                        continue;
                                    }
                                    ?>
                                    <div class="message <?php if ($_item->getHasError()): ?>message-error<?php else: ?>message-notice<?php endif; ?>">
                                        <?= $block->escapeHtml($message) ?>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif;?>

                    <?= $block->getItemExtraInfo($_item)->toHtml() ?>
                </tbody>
                <?php endforeach; ?>
        </table>
    </div>

    <?php if ($block->getQuoteViewModel()->isEditQuote($block->getQuoteId())):?>
        <div class="order-discounts">
            <?= $block->getButtonHtml(__('Update Items and Quantities'), 'quote.itemsUpdate()', 'action-secondary') ?>
        </div>
    <?php endif;?>

    <script>
        require([
            'Aheadworks_Ctq/js/quote/edit/form'
        ], function(){
            quote.itemsOnchangeBind()
        });
    </script>
<?php endif; ?>
