<style>
.input_container {
    position: relative;
   
   
}

.icon {
    position: absolute;
    bottom: 2px;
    right: 5px;
    width: 24px;
    height: 24px;
}
</style>

<?php if($block->checkCustomerStatus() || !$this->helper('MGS\Fbuilder\Helper\Data')->canShowFormLogin()): ?>
	<div class="login-form logged-customer" style="visibility:hidden; opacity:0">
		<button class="close-myaccount" id="close-myaccount"><span class="icon-close"></span></button>
		<?php echo $block->getChildHtml('top.link.header'); ?>
	</div>
<?php else: ?>
	<div class="login-form" style="visibility:hidden; opacity:0">
		<button class="close-myaccount" id="close-myaccount"><span class="icon-close"></span></button>
		<div class="block block-customer-login">
			<div class="block-title">
				<strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Login Your Account') ?></strong>
			</div>
			<div class="block-content" aria-labelledby="block-customer-login-heading">
				<form class="form form-login"
					  action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
					  method="post"
					  id="login-form-had"
					  data-mage-init='{"validation":{}}'>
					<?php echo $block->getBlockHtml('formkey'); ?>
					<div class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
						<div class="field email required">
							<div class="control">
								<input placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>"  autocomplete="on" id="email-had" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
							</div>
						</div>

						<div class="field password required">
							<div class="input_container">
								<input  placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass-had" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
								<span id="imgContrasena" class="fa fa-eye-slash icon" onclick="mostrarPassword();"></span>
								<a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot?') ?></span></a>
							</div>
						</div>						



						<?php echo $block->getChildHtml('form.additional.info.header'); ?>
						<div class="actions-toolbar">
							<div class="primary">
								<button type="submit" class="login btn btn-primary" name="send" id="send2-had"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button>
							</div>
							<div class="secondary">
							<a class="btn btn-link icon-right" href="https://www.siglo21.net/customer/account/forgotpassword/" target="_blank"><span>¿Olvidó su contraseña?</span></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
<?php endif ?>
<script>



		require(["jquery"], function($){
			var bandera= false;

			$("#imgContrasena").click(function () {
				var cambio = document.getElementById("pass-had");
				if(cambio.type == "password"){
				cambio.type = "text";
				$('.icon').removeClass('fa fa-eye-slash').addClass('fa fa-eye');
				}else{
				cambio.type = "password";
				$('.icon').removeClass('fa fa-eye').addClass('fa fa-eye-slash');
				}
			})

			$('#email-had, #pass-had').focusin(function() {
				bandera=true;
			});

			$('#email-had, #pass-had').focusout(function() {
				bandera=false;
			});
			
			$('#email-had, #pass-had').change(function() {
				bandera=false;
			})

			$(".header-top-links").mouseenter(function() {
				$('.header-area .header-top-links .login-form').css({"visibility":"visible", "opacity":"1"})
			});

			$(".header-top-links").mouseleave(function() {
				if(!bandera){
					$('.header-area .header-top-links .login-form').css({"visibility":"hidden", "opacity":"0"});
				}
			});
		});
</script>