<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Item\Price\Renderer */

$isLogged = $this->helper('Aventi\ManagerPrice\Helper\Data')->_getIsLogged();

$_item = $block->getItem();
?>
<span class="price-excluding-tax" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
    <span class="cart-price">
        <?php
            if ($isLogged) {
                echo $block->escapeHtml(
                    $this->helper(Magento\Checkout\Helper\Data::class)->formatPrice($_item->getRowTotal()),
                    ['span']
                );
            }
        ?>
    </span>
</span>
