<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$post = $block->getCurrentPost();
$collection = $block->getCollection();
$showAction = $this->getConfig('general_settings/show_action');
$categoryId = (int)$this->getRequest()->getParam('category_id', false);
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config'); 
$rtl = $themeSettingConfig->getStoreConfig('themesettings/general/rtl_theme') ? 'true' : 'false';
?>
<div class="blog-view blog-post-item">
	<div class="post-item entry single-entry">
		<div class="post-images entry-media">
			<?php if ($helper->getGalleryImage($post)): ?>
				<?php if(count($helper->getGalleryImage($post)) > 1): ?>
					<div class="gallery-image-carousel owl-carousel gallery-open-owlcarousel">
						<?php foreach($helper->getGalleryImage($post) as $_img): ?>
							<a class="gallery_image" href="<?= $_img; ?>" 
								style="background-image: url('<?= $_img; ?>')">
								<img src="<?= $_img; ?>" alt="" class="img-fluid"/>
							</a>
						<?php endforeach ?>
					</div>
					<script type="text/javascript">
						require([
							'jquery',
							'mgsowlcarousel'
							], function($){			
								$(document).ready(function(){
									$(".gallery-open-owlcarousel").owlCarousel({
										items: 10,
										loop: true,
										nav: true,
										dots: false,
										autoplayTimeout: 5000,
										rtl: <?= $rtl ?>,
										autoplay: false,
										autoplayHoverPause: true,
										margin: 0,
										autoHeight:true,
										responsive:{
											0:{
												items: 1
											},
											576:{
												items: 1
											},
											767:{
												items: 1
											},
											992:{
												items: 1						
											}
										}
									});
								});  	
							});		
						
						require([
							'jquery',
							'magnificPopup'
						], function(jQuery){
							(function($) {
								$(document).ready(function() {
									$('.gallery-image-carousel').magnificPopup({
										delegate: '.owl-item:not(.cloned) a',
										type: 'image',
										tLoading: 'Loading image #%curr%...',
										mainClass: 'mfp-img-gallery',
										fixedContentPos: true,
										gallery: {
											enabled: true,
											navigateByImgClick: true,
											preload: [0,1]
										},
										image: {
											tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
											titleSrc: function(item) {
											return item.el.attr('title');
											}
										}
									});
								});
							})(jQuery);
						});
					</script>
					<?php else: ?>
						<div class="gallery-image-carousel owl-carousel">
						<?php foreach($helper->getGalleryImage($post) as $_img): ?>
							<a class="gallery_image" href="<?= $_img; ?>" 
								style="background-image: url('<?= $_img; ?>')">
								<img src="<?= $_img; ?>" alt="" class="img-fluid"/>
							</a>
						<?php endforeach ?>
					</div>
					<?php endif; ?>
				<?php else: ?>
				<?php if($helper->getImagePost($post) != ""): ?>
					<div class="post-thumbnail">
						<?php if($post->getImageType() == "video" && $post->getVideoBigId() != ""): ?>
							<a class="post-thumbnail--image popup-video" href="<?= $helper->getVideoThumbUrl($post); ?>" title="<?= $post->getTitle(); ?>">
								<img class="img-fluid" src="<?= $helper->getImagePost($post); ?>" alt="<?= $post->getTitle(); ?>"/>
							</a>
							<div class="blog-list-video">
								<?php if($post->getImageType() == "video" && $post->getVideoBigId() != ""): ?>
									<a class="btn btn-primary popup-video" href="<?= $helper->getVideoThumbUrl($post); ?>"></a>
								<?php endif ?>
							</div>
							<?php else: ?>
								<a class="post-thumbnail--image" href="<?= $post->getPostUrlWithNoCategory(); ?>" title="<?= $post->getTitle(); ?>">
									<img class="img-fluid" src="<?= $helper->getImagePost($post); ?>" alt="<?= $post->getTitle(); ?>"/>
								</a>
						<?php endif ?>
					</div>
				<?php endif ?>
			<?php endif ?>
		</div>
		<?php if ($post->getContent()): ?>
			<div class="post-content entry-body">
				<div class="post-metas entry-meta">
					<span class="entry-author">
                        by <a href="#"><?php echo  $post->getUser(); ?></a>
                    </span>
                    <span class="meta-separator">|</span>
                    <a href="#"><?= $block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false); ?></a>
                    <span class="meta-separator">|</span>
                    <a href="#">2 Comments</a>
				</div>
				<h2 class="entry-title">
                    <a class="post-title-link" title="<?= $post->getTitle(); ?>" href="<?= $post->getPostUrlWithNoCategory(); ?>"><?= __($post->getTitle()); ?></a>
                </h2>
				<?php if($post->getTags()): ?>
				<?php 
					$arrayTags = explode( ',', $post->getTags());
				?>
				
				<div class="entry-cats">
                    in 
                    <?php foreach($arrayTags as $key => $tag): ?>
                    	<?php if($key == (count($arrayTags) - 1)): ?>
                    		<a href="#"> <?php echo $tag; ?></a>
                    	<?php else: ?>
                    		<a href="#"> <?php echo $tag; ?></a>,
                    	<?php endif; ?>
                    <?php endforeach; ?>
                </div>
            	<?php endif; ?>
            	<div class="content-description entry-content editor-content">
					<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
					<?= $objectManager->get('\Magento\Cms\Model\Template\FilterProvider')->getBlockFilter()->filter($post->getContent()); ?>
				</div>
				<div class="entry-footer row no-gutters flex-column flex-md-row">
					<div class="entry-tags">
						<?php $tags = $block->getTags(); ?>
						<?php if (count($tags)): ?>
							<span>Tags:</span>
							<?php foreach ($tags as $tag => $count): ?>
								<a href="#"><?= $tag; ?></a>
							<?php endforeach; ?>
						<?php endif; ?>
					</div><!-- End .entry-tags -->

					<div class="social-icons social-icons-color">
						<span class="social-label">Share this post:</span>
						<?php $themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config'); ?>
						<?php echo $themeSettingConfig->getStoreConfig('themesettings/sharethis/html_share'); ?>
					</div><!-- End .soial-icons -->
				</div>
			</div>
		<?php endif; ?>
		
	</div>	
	<?php if($showAction): ?>
		<div class="post-actions pager-nav">
			<?php $prevPost = $this->getPrevPost($post->getId()); ?>
			<?php if($post->getId() != $prevPost['id']): ?>
				
				<a class="pager-link pager-link-prev" href="<?= $prevPost['url']; ?>">
					<?= __('Previous Post'); ?>
					<span class="pager-link-title"><?= __($prevPost['name']) ?></span>
				</a>
			<?php endif ?>
			<?php $nextPost = $this->getNextPost($post->getId()); ?>
				<?php if($post->getId() != $nextPost['id']): ?>
					<a class="pager-link pager-link-next" href="<?= $nextPost['url']; ?>">
						<?= __('Next Post'); ?>
						<span class="pager-link-title"><?= __($nextPost['name']) ?></span>
					</a>
			<?php endif ?>
		</div>
	<?php endif ?>
	<?php $relatedPosts = $block->getRelatedPosts($post->getId()); ?>
	<?php if($relatedPosts): ?>
	<div class="related-post-list blog-grid related-posts owl-simple">
		<h3 class="title"><?= __('Related Posts')?></h3>
		<div class="clear-padding-owl">
			<div class="item related-images line owl-carousel">
				<?php foreach($relatedPosts as $_post): ?>
					<div class="post-images entry entry-grid">
						<div class="post-thumbnail pd-left-15 pd-right-15 entry-media">
							<a class="post-thumbnail--image full-width" href="<?= $_post->getPostUrlWithNoCategory(); ?>" style="background-image:url('<?= $helper->getImageThumbnailPost($_post); ?>');" title="<?= $_post->getTitle(); ?>">
								<img class="img-fluid" src="<?= $helper->getImageThumbnailPost($_post); ?>" alt="<?= $_post->getTitle(); ?>"/>
							</a>
						</div>
						<div class="entry-body">
							<div class="entry-meta">
								<a href="#"><?= $block->formatDate($_post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false); ?></a>
								<span class="meta-separator">|</span>
								<a href="#">2 Comments</a>
							</div><!-- End .entry-meta -->

							<h2 class="entry-title">
								<a href="<?= $_post->getPostUrlWithNoCategory(); ?>"><?= $_post->getTitle(); ?></a>
							</h2><!-- End .entry-title -->

							<?php if($post->getTags()): ?>
							<?php 
								$arrayTags = explode( ',', $post->getTags());
							?>
							
							<div class="entry-cats">
								in 
								<?php foreach($arrayTags as $key => $tag): ?>
									<?php if($key == (count($arrayTags) - 1)): ?>
										<a href="#"> <?php echo $tag; ?></a>
									<?php else: ?>
										<a href="#"> <?php echo $tag; ?></a>,
									<?php endif; ?>
								<?php endforeach; ?>
							</div>
							<?php endif; ?>
						</div>
						<script type="text/javascript">
							require([
								'jquery',
								'mgsowlcarousel'
								], function($){			
									$(document).ready(function(){
										$(".related-images").owlCarousel({
											items: 10,
											loop: false,
											nav: false,
											dots: true,
											autoplayTimeout: 5000,
											rtl: <?= $rtl ?>,
											autoplay:false,
											autoplayHoverPause: true,
											margin: 20,
											responsive:{
												0:{
													items: 1
												},
												576:{
													items: 1
												},
												767:{
													items: 3
												},
												992:{
													items: 3						
												}
											}
										});
									});  	
								});		
						</script>
					</div>
				<?php endforeach ?>
			</div>
		</div>
	</div>
	<?php endif ?>
	<?= $block->getChildHtml('post_view_comment'); ?>
</div>
