
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
$count = $_helper->getItemCount();
?>

<div class="block-compare">
    <div class="block-title">
        <a class="action showcompare theme-header-icon" href="<?php /* @escapeNotVerified */ echo $block->getUrl().'catalog/product_compare/index/'; ?>">
			<i class="icon-random"></i>
			<?php if($count > 0): ?>
				<span class="counter qty"><?php echo $count ?></span>
			<?php endif; ?>
			<span class="label">
				<?= __('Compare'); ?>
            </span>
		</a>
        
    </div>
    <div class="block-content" aria-label="block-compare-heading">
        <?php if($_helper->getItemCount() > 0): ?>
            <ol id="compare-items" class="product-items product-items-names"
                data-mage-init='{"compareItems":{
                    "removeConfirmMessage":"<?php echo __("Are you sure you would like to remove this item from the compare products?") ?>",
                    "removeSelector":"#compare-items a.action.delete",
                    "clearAllConfirmMessage":"<?php echo __("Are you sure you would like to remove all products from your comparison?") ?>",
                    "clearAllSelector":"#compare-clear-all"
                }}'>
					<?php foreach($_items as $_index => $_item): ?>
					<li class="product-item">
						<input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>"/>
						<strong class="product-item-name">
							<a href="<?php echo $this->getProductUrl($_item) ?>" class="product-item-link">
								<?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_item, $_item->getName(), 'name') ?>
							</a>
						</strong>
						<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>

						<a href="#" data-post='<?php echo $compareHelper->getPostDataRemove($_item); ?>'
						   title="<?php echo __('Remove This Item') ?>"
						   class="action delete">
							<span><?php echo __('Remove This Item') ?></span></a>
					</li>
				<?php endforeach; ?>
			</ol>
			<div class="actions-toolbar">
				<div class="primary">
					<a id="compare-clear-all" href="#" data-post='<?php echo $_helper->getPostDataClearList() ?>' class="action clear">
						<span><?php echo __('Clear All') ?></span>
					</a>
				</div>
				<div class="secondary">
					<a href="<?php echo $_helper->getListUrl() ?>" class="btn compare btn-default icon-right"><span><?php echo __('Compare') ?></span></a>
				</div>
			</div>
		<?php else: ?>
			<div class="empty"><?php echo __('You have no items to compare.') ?></div>
		<?php endif; ?>
	</div>	
</div>