<?php
//header("Access-Control-Allow-Origin: *");
//header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
//header("Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token, Authorization");

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST");
header("Access-Control-Allow-Headers: X-Pardux-Authorization");
header("Access-Control-Allow-Credentials: true");

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

if ($customerSession->isLoggedIn()) {
    $customerName = $customerSession->getCustomer()->getName();
    $customerEmail = $customerSession->getCustomer()->getEmail();
    $customerIdentification = $customerSession->getCustomer()->getIdentificationCustomer();

} else {
    echo "¡Hola, visitante!";

    $customerName = "";
    $customerEmail = "";
    $customerIdentification = "";
  }

$token = "111111";
$escapedCustomerIdentification = urlencode($customerIdentification);
$escapedToken = urlencode($token);

$iframeSrc = "https://credito.siglo21.net:8011?&ruc=$escapedCustomerIdentification&token=$escapedToken";
?>


<iframe src="<?php echo $iframeSrc; ?>" width="100%" height="1270" style="border: none;"></iframe>

<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            
            var authToken = "3551f43bcea070b0cc642032622f34dc799a1cfbb0ce4026c4714823917ff816";
            var postData = {
                "identifier": "0932004849001"
            };
            var headers = {
                'X-Pardux-Authorization': authToken
            };

            $.ajax({
                url: 'https://app.pardux.com/api/loyalty/tracking',
                crossDomain: true,
                xhrFields:{    
                        withCredentials: false  
                    },
                method: 'POST',
                dataType: 'json',
                data: JSON.stringify(postData),
                contentType: 'application/json',
                headers: headers,
                success: function(response) {
                    console.log(response);
                },
                error: function(xhr, status, error) {
                    console.error(error);
                }
            });
        });
    });
</script>





