<?php

use Magento\Framework\App\Action\Action;

$isLogged = $this->helper('Aventi\ManagerPrice\Helper\Data')->_getIsLogged();
$image = 'category_page_grid';

$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$_product = $this->getLoadProduct();
$_productNameStripped = $block->stripTags($_product->getName(), null, true);
$listMaterial = ($_product->getCustomAttribute('list_material')) ? $_product->getCustomAttribute('list_material')->getValue() : 0;
$inventoryBlock = $this->getLayout()->createBlock("Aventi\ShowInventory\Block\Product\Inventory");
$productImage = $block->getImage($_product, $image);
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$hideName = $this->getBlockData('hide_name');

$hidePrice = $this->getBlockData('hide_price');
$hideAddCart = $this->getBlockData('hide_addcart');
$hideAddWishlist = $this->getBlockData('hide_addwishlist');
$hideAddCompare = $this->getBlockData('hide_addcompare');
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$themeHelperImage = $this->helper('MGS\ThemeSettings\Helper\Image');
$lazyLoad = $themeSettingConfig->getStoreConfig('themesettings/general/lazy_load');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

?>



<div class="product-item-info <?php if ($isLogged) :?>login<?php endif; ?>" data-container="product-grid">
		<?php echo $themeSettingConfig->getProductLabel($_product); ?>

	    <?php
		$productImage = $block->getImage($_product, $image);

		$productImageFirst = $productImage = $_imagehelper->init($_product, $image)->getUrl();
		
		?>
		<div class="product-top">
			<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
				<?php $imgAlt = $_product->getName(); ?>
				<span class="product-image-container">
					<span class="<?php if ($lazyLoad): ?>parent_lazy<?php endif; ?> product-image-wrapper" style="padding-bottom: <?php /* @escapeNotVerified */ echo ($themeHelperImage->getRatio() * 100); ?>%;">

						<img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid product-image-photo <?php if($lazyLoad): ?>lazy <?php endif; ?>" data-src="<?php echo $productImage ?>" />
				
						
					</span>
				</span>
			</a>
			<?php if(($hideAddCart!=1) || ($hideAddWishlist!=1) ||($hideAddCompare!=1)): ?>
				<div class="product-item-inner">
					<div class="product actions product-item-actions">
            <?php if ($isLogged) :?>
              <?php if($hideAddCart!=1): ?>
                <div class="actions-primary">
                  <?php if ($_product->isSaleable()): ?>
                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                    <form id="tocart<?php echo $_product->getId() ?>" data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                      <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                      <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                      <?php if($this->getIsAjax()): ?>
                        <?php
                          $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                          $FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');
                        ?>
                        <input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
                        <button type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" onclick="ajaxCart('tocart<?php echo $_product->getId() ?>')" class="action tocart primary">
                          <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                        </button>
                      <?php else: ?>
                        <?= $block->getBlockHtml('formkey') ?>
                        <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary">
                          <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                        </button>
                      <?php endif ?>

                    </form>
                  <?php else: ?>
                    <?php if ($_product->isAvailable()): ?>
                      <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                    <?php else: ?>
                      <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                    <?php endif; ?>
                  <?php endif; ?>
                </div>
              <?php endif; ?>
						<?php endif; ?>
						<?php if(($hideAddWishlist!=1) ||($hideAddCompare!=1)): ?>
							<div data-role="add-to-links" class="actions-secondary">
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && ($hideAddWishlist!=1)): ?>
									<a href="#" class="action towishlist"  aria-label="<?= __('Save') ?>" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' data-action="add-to-wishlist" role="button">
										<span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
									</a>
								<?php endif; ?>
								<?php if($hideAddCompare!=1): ?>
									<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
									<a href="#" class="action tocompare" title="<?= $block->escapeHtml(__('Compare')) ?>" aria-label="<?= $block->escapeHtml(__('Compare')) ?>" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product) ?>' role="button">
										<span><?= /* @escapeNotVerified */ __('Compare') ?></span>
									</a>
								<?php endif ?>
							</div>
						<?php endif ?>
					</div>
				</div>
			<?php endif; ?>
		</div>

		<div class="product details product-item-details">

	
			<div class="product-brand">
				<a href=""><?php echo $_product->getResource()->getAttribute('mgs_brand')->getFrontend()->getValue($_product); ?></a>
			</div>
			<hr class="product-availability">

			<?php if($hideName!=1): ?>
				<strong class="product name product-item-name">
					<a class="product-item-link"
					   href="<?= $_product->getProductUrl() ?>">
						<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
					</a>
				</strong>
			<?php endif ?>
			<hr class="hover-displayed">
			<div class="product-refs hover-displayed">
				<?= $_product->getResource()->getAttribute('sku')->getFrontend()->getValue($_product) ?>
				<br>
				<?= $_product->getResource()->getAttribute('ref')->getFrontend()->getValue($_product) ?>
				
				<?php if($_product->getResource()->getAttribute('upc')->getFrontend()->getValue($_product)) : ?>
					<span class="label-upc">
						<strong><?= $_product->getResource()->getAttribute('upc')->getFrontend()->getLabel($_product) ?> : </strong> <?= $_product->getResource()->getAttribute('upc')->getFrontend()->getValue($_product) ?>
					</span>
				<?php endif; ?>
					
			</div>


			<?php if ($hidePrice != 1) : ?>
				<?= $block->getProductPrice($_product) ?>
				<span class="text-price-label">
					<?php echo __('Price without TAX') ?>
				</span>
				<?php if ($isLogged) : ?>
					<?php if($listMaterial): ?>
						<div class="content-inventory">
							<?php echo $inventoryBlock->displaySourceInventoryListMaterial($_product->getSku()) ?>
						</div>
					<?php else: ?>
						<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setKey($_product->getSku())->setTemplate("Aventi_ShowInventory::inventory-button.phtml")->toHtml() ?>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif ?>

			<?= $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>

		</div>
</div>


