<?php $attribute = NULL ?>
<?php if($this->getData('attribute')!=''): ?>
<?php $attribute = $this->getData('attribute'); ?>
<?php endif ?>
<?php $themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config'); ?>
<?php $_productCollection = $this->getProductByCategories($this->getCategoryIds(), $attribute, "bestseller") ?>
<?php $builderHelper = $this->helper('MGS\Fbuilder\Helper\Data'); ?>
<?php $blockType = $this->getData('block_type'); ?>
<?php $template = 'MGS_Fbuilder::products/grid_item.phtml'; ?>
<?php $effect = $themeSettingConfig->getStoreConfig('themesettings/category/product_hover_effect'); ?>
<?php $hideHoverMb = $themeSettingConfig->getStoreConfig('themesettings/catalog/hover_effect_mb'); ?>
<div class="content-block <?= $blockType ?>-product-cat-block">
	<?php // Block Content  ?>
	<?php if (isset($_productCollection) && $_productCollection->getSize()>0): ?>
		
		<?php $blockId = rand() . time(); ?>
		<?php $useSlider = $this->getUseSlider(); ?>
		<?php $items = $perRowDefault = $this->getPerrow(); ?>
		<?php $perRowTablet = $this->getPerrowTablet(); ?>
		<?php $perRowMobile = $this->getPerrowMobile(); ?>
		
		<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
			<?php $slideMultiRow = true; ?>
			<?php $slideBy = 1 ?>
			<?php $columnCount = $perRowDefault * $this->getNumberRow(); ?>
		<?php else: ?>
			<?php $slideBy = $this->getSlideBy() ?>
			<?php $slideMultiRow = false; ?>
		<?php endif ?>
		
		<?php if($useSlider): ?>
		
		<?php 
			$settingMode = 'multiple'; 
			$navPosition = $this->getNavigationPosition();
	
			$navType = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/navigation');
			if($navType=='image'){
				$nextIcon = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/next_image');
				$prevIcon = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/prev_image');
				$navHtml = '["<span><img src=\''.$builderHelper->getMediaUrl().'mgs/fbuilder/slider/'.$prevIcon.'\'/></span>", "<span><img src=\''.$builderHelper->getMediaUrl().'mgs/fbuilder/slider/'.$nextIcon.'\'/></span>"]';
			}elseif($navType=='font'){
				$nextIcon = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/next_font_class');
				$prevIcon = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/prev_font_class');
				$navHtml = '["<span><em class=\''.$prevIcon.'\'></em></span>", "<span><em class=\''.$nextIcon.'\'></em></span>"]';
			}else {
				$navHtml = '["<span></span>", "<span></span>"]';
				
			}
		?>
		<?php endif ?>
		
		<div class="block widget mgs-products <?= $blockType ?>-products-grid products-grid product-items <?php if($hideHoverMb): ?> hide-hover-mb <?php endif ?> <?php echo $effect; ?>">
			<div id="<?= $blockType ?>-products<?= $blockId; ?>" class="items<?php if($useSlider): ?> owl-carousel mgs-owl-carousel mgs-carousel-<?= $settingMode ?> nav-type-<?= $navType ?> nav-position-<?= $navPosition ?> <?php if($this->getHideNav() && ((($items==1) && ($navPosition!='middle-outside')) || (($items>1) && ($navPosition=='middle-inside')))): ?> autohide-nav<?php endif ?> dot-position-<?= $this->getPaginationPosition()?><?php else: ?> line row-<?= $perRowDefault ?> row-tablet-<?= $perRowTablet ?> row-mobile-<?= $perRowMobile ?><?php endif ?>">
			
					
			<div class="product product-item" style="margin:0;padding:0px">
				
					<div class="product-top">
						<a href="https://www.siglo21.net/catalogsearch/result/?q=speedmind" class="product photo product-item-photo" target="_blank" tabindex="-1">
								<span class="product-image-container">
									<span class=" product-image-wrapper" style="padding-bottom: 100%;">
										<img src="https://www.siglo21.net/media/marcas/speedmind.jpg" alt="spedmind" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/speedmind.jpg">
									</span>
								</span>
						</a>
					</div>
					<div class="product-top">
						<a href="https://www.siglo21.net/catalogsearch/result/?q=amd" class="product photo product-item-photo" target="_blank" tabindex="-1">
								<span class="product-image-container">
									<span class=" product-image-wrapper" style="padding-bottom: 100%;">
										<img src="https://www.siglo21.net/media/marcas/amd.png" alt="amd" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/amd.png">
									</span>
								</span>
						</a>
					</div>
			</div>
			<div class="product product-item" style="margin:0;padding:0px">
				<div class="product-top">
						<a href="https://www.siglo21.net/catalogsearch/result/?q=trust" class="product photo product-item-photo" target="_blank" tabindex="-1">
								<span class="product-image-container">
									<span class=" product-image-wrapper" style="padding-bottom: 100%;">
										<img src="https://www.siglo21.net/media/marcas/trust.jpg" alt="trust" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/trust.png">
									</span>
								</span>
						</a>
					</div>				

				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=hp" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/hp.jpg" alt="hp" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/hp.png">
								</span>
							</span>
					</a>

				</div>
			</div>
			<div class="product product-item" style="margin:0;padding:0px">
				
				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=lg0" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/lg.png" alt="lg" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/lg.png">
								</span>
							</span>
					</a>

				</div>
				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=dell" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/dell.png" alt="dell" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/dell.png">
								</span>
							</span>
					</a>
				</div>
			</div>		
			<div class="product product-item" style="margin:0;padding:0px">
				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=gopro" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/GOPRO.png" alt="gopro" class="img-fluid product-image-photo" data-src="https://www.siglo21.net/media/marcas/toshiba.png">
								</span>
							</span>
					</a>

				</div>

				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=samsung" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/samsung.png" alt="samsung" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/samsung.png">
								</span>
							</span>
					</a>

				</div>
				
			</div>	
			<div class="product product-item" style="margin:0;padding:0px">
				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=tplink" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/tplink.png" alt="tplink" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/tplink.png">
								</span>
							</span>
					</a>
				</div>
				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=canon" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/canon.png" alt="canon" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/canon.png">
								</span>
							</span>
					</a>
				</div>
			</div>		
			<div class="product product-item" style="margin:0;padding:0px">
				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=dlink" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/dlink.png" alt="dlink" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/dlink.png">
								</span>
							</span>
					</a>
				</div>

				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=epson" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/epson.png" alt="epson" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/epson.png" />
								</span>
							</span>
					</a>
				</div>
			</div>
			<div class="product product-item" style="margin:0;padding:0px">
				
				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=genius" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/genius.png" alt="genius" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/genius.png">
								</span>
							</span>
					</a>
				</div>
				<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=gigabyte" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/gigabyte.png" alt="gigabyte" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/gigabyte.png">
								</span>
							</span>
					</a>
				</div>
		</div>
		<div class="product product-item" style="margin:0;padding:0px">
			
			<div class="product-top">
					<a href="https://www.siglo21.net/catalogsearch/result/?q=adata" class="product photo product-item-photo" target="_blank" tabindex="-1">
							<span class="product-image-container">
								<span class=" product-image-wrapper" style="padding-bottom: 100%;">
									<img src="https://www.siglo21.net/media/marcas/adata.png" alt="adata" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/adata.png">
								</span>
							</span>
					</a>

			</div>
			<div class="product-top">
				<a href="https://www.siglo21.net/catalogsearch/result/?q=sony" class="product photo product-item-photo" target="_blank" tabindex="-1">
						<span class="product-image-container">
							<span class=" product-image-wrapper" style="padding-bottom: 100%;">
								<img src="https://www.siglo21.net/media/marcas/sony.jpg" alt="sony" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/sony.jpg">
							</span>
						</span>
				</a>

			</div>
		</div>
		<div class="product product-item" style="margin:0;padding:0px">
					<div class="product-top">
						<a href="https://www.siglo21.net/catalogsearch/result/?q=asus" class="product photo product-item-photo" target="_blank" tabindex="-1">
								<span class="product-image-container">
									<span class=" product-image-wrapper" style="padding-bottom: 100%;">
										<img src="https://www.siglo21.net/media/marcas/ASUS.png" alt="ASUS" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/ASUS.png">
									</span>
								</span>
						</a>
					</div>			

			<div class="product-top">
				<a href="https://www.siglo21.net/catalogsearch/result/?q=cdp" class="product photo product-item-photo" target="blank" tabindex="-1">
						<span class="product-image-container">
							<span class=" product-image-wrapper" style="padding-bottom: 100%;">
								<img src="https://www.siglo21.net/media/marcas/cdp.jpg" alt="a" class="img-fluid product-image-photo " data-src="https://www.siglo21.net/media/marcas/lenovo.png">
							</span>
						</span>
				</a>
			</div>
		</div>	
	</div>
</div>
		
		<?php if($useSlider): ?>
			<?php $autoPlay = $this->getAutoplay() ? 'true' : 'false'; ?>
			<?php $stopAuto = $this->getStopAuto() ? 'true' : 'false'; ?>
			<?php $nav = $this->getNavigation() ? 'true' : 'false'; ?>
			<?php $dot = $this->getPagination() ? 'true' : 'false'; ?>
			<?php $rtl = $this->getRtl() ? 'true' : 'false'; ?>
			<?php $loop = $this->getLoop() ? 'true' : 'false'; ?>
			<?php $slideBy = $slideBy ? $slideBy : 1; ?>
			
			<script type="text/javascript">
				require([
					'jquery',
					'mgsowlcarousel'
				], function ($) {
					var owl<?= $blockType ?>cattab<?= $blockId ?> = $('#<?= $blockType ?>-products<?= $blockId ?>').owlCarousel({
						<?php if($slideMultiRow): ?>
							items: 1,
						<?php else: ?>
							items: <?= $perRowDefault; ?>,
						<?php endif ?>
						autoplay: <?= $autoPlay ?>,
						autoplayHoverPause: <?= $stopAuto ?>,
						nav: <?= $nav ?>,
						dots: <?= $dot ?>,
						slideBy: <?= $slideBy ?>,
						rtl: <?= $rtl; ?>,
						loop: <?= $loop; ?>,
						<?php if(!$slideMultiRow):?>margin: <?= $this->getSlideMargin() ?>,<?php endif ?>
						<?php if($navPosition=='top-left' || $navPosition=='top-right'): ?>
							onInitialized: function(){
								$("#<?= $blockType ?>-products<?= $blockId ?> .owl-nav").attr('style', 'top:<?= $this->getNavTop() ?>px');
							},
						<?php endif ?>
						<?php if(!$slideMultiRow): ?>
						responsive:{
							0:{
								items:4,
								nav: false,
							},
							571:{
								items:4
							},
							1200:{
								items:9	
							}
						},
						<?php endif ?>
						navText: <?= $navHtml ?>,
						autoHeight:true
					});
				});
			</script>
		<?php endif ?>
	<?php else: ?>
		<div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
	<?php endif ?>
</div>