<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="quote-list cart-empty">
    <p><?= $block->escapeHtml(__('You have no items in your quote list.')) ?></p>
    <p><?= $block->escapeHtml(
        __(
            'Click <a href="%1">here</a> to continue shopping.',
            $block->escapeUrl($block->getContinueShoppingUrl())
        ),
        ['a']
    ) ?>
    </p>
</div>
