<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \MGS\InstantSearch\Block\SearchResult\ListProduct
 */
?>
<?php $themeHelperImage = $this->helper('MGS\ThemeSettings\Helper\Image'); ?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$limit = $block->getPositionLimit();
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$perRowDefault = $themeSettingConfig->getStoreConfig('instantsearch/general/per_row');
$perRowTablet = $themeSettingConfig->getStoreConfig('instantsearch/general/per_row_tablet');
$perRowMobile = $themeSettingConfig->getStoreConfig('instantsearch/general/per_row_mobile');
$hoverChange = $themeSettingConfig->getStoreConfig('themesettings/catalog/hover_change');
$effect = $themeSettingConfig->getStoreConfig('themesettings/category/product_hover_effect');
$dataHelper = $this->helper('MGS\AjaxCart\Helper\Data');
$isLogged = $this->helper('Aventi\ManagerPrice\Helper\Data')->_getIsLogged();
?>
<!-- Hide Element -->
<?php
$hideReview = $themeSettingConfig->getStoreConfig('themesettings/catalog/review');
$hideAddCart = $themeSettingConfig->getStoreConfig('themesettings/catalog/add_to_cart');
$hideWishlist = $themeSettingConfig->getStoreConfig('themesettings/catalog/wishlist_button');
$hideCompare = $themeSettingConfig->getStoreConfig('themesettings/catalog/compare_button');
$hideHoverMb = $themeSettingConfig->getStoreConfig('themesettings/catalog/hover_effect_mb');

$buttonTitle = __('Add to Quote');
$viewModel = $block->getQuoteListViewModel();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');


?>
<div class="products-result">
<div class="block block-title">
    <h4><?= __('Products') ?></h4>
</div>
<?php if (!$_productCollection->count()): ?>
    <div class="wrapper message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = $block->showShortDescription();
        $showReview = $block->showReview();
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
    ?>
	<div class="products active-slider wrapper <?php if ($hideHoverMb) : ?> hide-hover-mb <?php endif ?> <?php echo $effect; ?> <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php $iterator = 1; ?>
		<ol class="line products items product-items row-<?=$perRowDefault; ?> row-tablet-<?=$perRowTablet; ?> row-mobile-<?=$perRowMobile; ?> ">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            	<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product product-item col">' : '</li><li class="product product-item col">' ?>
            	<div class="product-item-info  <?php if ($isLogged) :?>login<?php endif; ?> " data-container="product-grid">
                    <?php
					$productImage = $block->getImage($_product, $image);
					$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
					if ($pos != null) {
						$position = ' style="left:' . $productImage->getWidth() . 'px;'
							. 'top:' . $productImage->getHeight() . 'px;"';
					}
					$productImageFirst = $productImage = $_imagehelper->init($_product, $image)->getUrl();
					if ($hoverChange) {
						$productImageHoverFirst = $productImageHover = $_imagehelper->init($_product, 'product_base_image')->getUrl();
					}
					?>
					<?php if ($effect = 'effect2' || $effect = 'effect4') : ?>
						<div class="action-wishlist">
						</div>
					<?php endif ?>
                    <?php // Product Image ?>
					<div class="product-top <?php if ($hideCompare && $hideAddCart) : ?> hide-inner-action-mb  <?php endif ?>">
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
								<span class="product-image-container">
									<span class="parent_lazy product-image-wrapper lazy_loaded" style="padding-bottom: <?php /* @escapeNotVerified */ echo ($themeHelperImage->getRatio() * 100); ?>%;">
										<img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid product-image-photo lazy " data-src="<?php echo $productImage ?>" />
										<?php if ($hoverChange) : ?>
											<?php if (basename($_product->getData('base_image')) !=  'no_selection') : ?>
												<?php if (basename($_product->getData('base_image')) != basename($_product->getData('small_image'))) : ?>
													<img src="<?php echo $productImageHoverFirst ?>" alt="<?php echo $imgAlt ?>" class="img-fluid img-hover-show lazy" data-src="<?php echo $productImageHover ?>" />
												<?php endif ?>
											<?php endif ?>
										<?php endif ?>
									</span>
								</span>
							</a>
							<div class="product-item-inner">
								<div class="product actions <?php if ($hideCompare) : ?> hide-compare  <?php endif ?> <?php if ($hideAddCart) : ?> hide-action-cart  <?php endif ?> product-item-actions" <?= strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<?php if ($isLogged) : ?>
										<?php if (!$hideAddCart) : ?>
											<div class="actions-primary" <?= strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
												<?php if ($_product->isSaleable()) : ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
														<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?= $block->getBlockHtml('formkey') ?>
															<button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
																<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
															</button>
														</form>
												<?php else : ?>
													<?php if ($_product->getIsSalable()) : ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else : ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										<?php endif ?>
									<?php endif ?>


                                    <!-- BOTON ADD TO QUOTE -->
                                    <!--<?php if ($_product && $_product->isSaleable() /* && $viewModel && $viewModel->isAllowedToAdd()*/): ?>
                                        <button type="button"
                                                title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                                                class="action primary toquotelist"
                                                id="product_addtoquotelist_button"
                                                data-mage-init='{"awCtqAddToQuoteListButton": {"isProductPage": true}}'
                                                disabled>
                                            <span><?= $block->escapeHtml($buttonTitle) ?></span>
                                        </button>
                                    <?php endif; ?>-->
                                    <!-- END ADD TO QUOTE -->


									<div data-role="add-to-links" class="actions-secondary " <?= strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
										<?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
											<?= $addToBlock->setProduct($_product)->getChildHtml(); ?>
										<?php endif; ?>
									</div>
								</div>
							</div>
						</div>
						<div class="product details product-item-details">
							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							$cateLink = $themeSettingConfig->getCate($_product);
							?>
							<?php if ($cateLink) : ?>
								<div class="product-cate">
									<?php echo $cateLink; ?>
								</div>
							<?php endif ?>
							<strong class="product name product-item-name">
								<a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</strong>
							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
							<span class="text-price-label">
								<?php echo __('Price without TAX') ?>
							</span>
							<?php if(!$hideReview): ?>
								<?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
							<?php endif ?>

							<?= $block->getProductDetailsHtml($_product); ?>
							<?php if ($showDescription) : ?>
								<div class="product description product-item-description">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								</div>
							<?php endif; ?>
						</div>
            	</div>
            	<?=($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
		 <?php if($_productCollection->count() && $_productCollection->getSize() > $limit): ?>
			<div class="view-more border-radius">
				<a class="action secondary" href="<?php /* @escapeNotVerified */ echo $block->getResultUrl() ?>"><?php /* @escapeNotVerified */ echo $block->getViewMoreLabel() ?></a>
			</div>
		<?php endif; ?>
	</div>

    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
</div>
