<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Catalog\Block\Product\View
 */

$isLogged = $this->helper('Aventi\ManagerPrice\Helper\Data')->_getIsLogged();
?>
<?php $_product = $block->getProduct(); ?>
<?php $themeHelper = $this->helper('MGS\ThemeSettings\Helper\Config'); ?>
<?php $glrTemplate = $themeHelper->getStoreConfig('extragallery/general/glr_type'); ?>
<?php $inventoryBlock = $this->getLayout()->createBlock("Aventi\ShowInventory\Block\Product\Inventory"); ?>
<?php $productType = $_product->getTypeId(); ?>
<?php $listMaterial = ($_product->getCustomAttribute('list_material')) ? $_product->getCustomAttribute('list_material')->getValue() : 0; ?>
<?php
if ($_product->getData('extragallery_glr_type')) {
    $glrTemplate = $_product->getData('extragallery_glr_type');
}
?>

<?php if ($_product->getMgsDetailTemplate() == ""): ?>
	<?php $templateLayout = $themeHelper->getStoreConfig('themesettings/product_details/default_template'); ?>
<?php else: ?>
	<?php $templateLayout = $_product->getMgsDetailTemplate(); ?>
<?php endif ?>

<?php if ($_product->isSaleable()): ?>
	<div class="box-tocart" style="<?php if (!$isLogged):?>margin-bottom: 10px;<?php endif; ?>">
		<br>
		<div class="fieldset">
			<?php if ($isLogged) :?>
				<?php if ($block->shouldRenderQuantity()): ?>
					<div class="field qty">
						<label for="qty"><?php echo __('Qty'); ?>:</label>
						<div class="qty-pr">
							<div class="input-group-prepend">
								<button style="min-width: 26px" class="edit-qty minus disable-select-text btn btn-decrement btn-spinner" onclick="minusQty('qty')" type="button">
									<i class="icon-minus"></i>
								</button>
							</div>
							<!-- <span class="edit-qty minus disable-select-text" onclick="minusQty('qty')"><i class="icon-minus"></i></span> -->
							<input type="number"
								   name="qty"
								   id="qty"
								   maxlength="12"
								   value="<?= $block->getProductDefaultQty() * 1 ?>"
								   title="<?= __('Qty') ?>" class="input-text qty"
								   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
								   />
							<!-- <span class="edit-qty plus disable-select-text" onclick="plusQty('qty')"><i class="icon-plus"></i></span> -->
							<div class="input-group-append">
								<button style="min-width: 26px" class="edit-qty plus disable-select-text btn btn-increment btn-spinner" onclick="plusQty('qty')" type="button">
									<i class="icon-plus"></i>
								</button>
							</div>
						</div>
					</div>
				<?php endif; ?>	  		
				<div class="inventory-container">
					<?php if($listMaterial): ?>					
						<div class="content-inventory">										
							<?php echo $inventoryBlock->displaySourceInventoryListMaterial($_product->getSku()) ?>
						</div>			
					<?php else: ?>	
						<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setKey($_product->getSku())->setTemplate("Aventi_ShowInventory::inventory-button.phtml")->toHtml() ?>
						<?php if($productType == 'simple'): ?>
							<div class="content-inventory">										
								<?php echo $inventoryBlock->displaySourceInventoryByCity($_product->getSku()) ?>
							</div>
						<?php endif; ?>	
					<?php endif; ?>
				</div>
				<div class="actions">
					<button type="submit"
						title="<?= __('Add To Cart') ?>"
						class="action primary tocart btn btn-default  btn-product btn-cart"
						id="product-addtocart-button">
						<span><?= __('Add To Cart') ?></span>
					</button>
				</div>
				<?= $block->getChildHtml('', true) ?>
	      	<?php else: ?>
				<div class="actions-not-logged">
					<a class="btn btn-default"
						href="<?= $block->getUrl('customer/account/login'); ?>">
						<span><?= __('Login') ?></span>
					</a>
				</div>
			<?php endif; ?>
		</div>
		<?php if (!$isLogged) :?>
			<div>
				<span><?= __('Login to see prices and to buy');?></span>
				<br>
				<a href="<?= $block->getUrl('customer/account/create'); ?>"><span>¿No eres cliente de Siglo 21?</span></a>
			</div>
		<?php endif; ?>
	</div>
<?php endif; ?>
<?php if(!$isLogged): ?>
	<script>
		require(["jquery"], function($) {
			$('.product-info-price').hide();
		});
	</script>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<?php if ($block->shouldRenderQuantity()): ?>
	<script type="text/javascript">
		function plusQty(qtyInput){
			require([
			'jquery'
			], function($){
				if($('#'+qtyInput).attr('disabled')!='disabled'){
					qty = $('#'+qtyInput).attr('value');
					qty = parseInt(qty);
					qty++;
					$('#'+qtyInput).val(qty);
					$('#sticky_qty').val(qty);
				}
			});

		}
		function minusQty(qtyInput){
			require([
			'jquery'
			], function($){
				if($('#'+qtyInput).attr('disabled')!='disabled'){
					qty = $('#'+qtyInput).attr('value');
					qty = parseInt(qty);

					if(qty>1){
						qty--;
						$('#'+qtyInput).val(qty);
						$('#sticky_qty').val(qty);
					}
				}
			});
		}
	</script>
<?php endif; ?>
