<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form">
    <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <?= $block->getBlockHtml('formkey')?>
        <?= $block->getChildHtml('form_top'); ?>
        <?php // If is deals product. Show countdown time ?>
        <?php if($_product->getSpecialPrice() && $_product->getSpecialToDate() && $_product->getSpecialFromDate()): ?>
            
            <?php $themeHelper = $this->helper('MGS\ThemeSettings\Helper\Config'); ?>
            <?php $dateTimeFormat = \Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT; ?>
            <?php $now = $themeHelper->getCurrentDateTime(); ?>
            <?php $specialFromDate = date($dateTimeFormat, strtotime($_product->getSpecialFromDate())); ?>
            <?php $specialToDate = date($dateTimeFormat, strtotime($_product->getSpecialToDate())); ?>
            
            <?php if($specialFromDate <= $now && $specialToDate > $now): ?>
                <div class="product-detail-deals margin-top25">
                    <?= $this->getLayout()
                                    ->createBlock('Magento\Framework\View\Element\Template')
                                    ->setProduct($_product->getId())
                                    ->setTimeNow($now)
                                    ->setSpecialFromDate($specialFromDate)
                                    ->setSpecialToDate($specialToDate)
                                    ->setTemplate('MGS_ThemeSettings::products/deals/countdown_detail.phtml')
                                    ->toHtml() ?>
                </div>
            <?php endif ?>
            
        <?php endif ?>
        <?php // End Deals ?>
        <?php if (!$block->hasOptions()):?>
            <?= $block->getChildHtml('product_info_form_content'); ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?= $block->getChildHtml('form_bottom'); ?>
    </form>
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId())?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
    });
</script>
