<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<div class="admin__page-section-title">
    <span class="title"><?= /* @escapeNotVerified */ $block->getHeaderText() ?></span>
    <?php if($block->getButtonsHtml()): ?>
        <div class="actions"><?= $block->getButtonsHtml() ?></div>
    <?php endif; ?>
</div>

<?= $block->getChildHtml('', true) ?>
