<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/**
 * @var $block \Aheadworks\CreditLimit\Block\Payment\Info
 */
?>
<div class="aw-credit-limit-payment-method-name"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></div>
<?php if ($block->getPoNumber()) : ?>
    <table class="data-table admin__table-secondary">
        <tr>
            <th><?= $block->escapeHtml(__('Purchase Order Number')) ?>:</th>
            <td><?= $block->escapeHtml($block->getPoNumber()) ?></td>
        </tr>
    </table>
<?php endif; ?>

