<?php $attribute = NULL ?>
<?php if($this->getData('attribute')!=''): ?>
	<?php $attribute = $this->getData('attribute') ?>
<?php endif ?>
<?php $_productCollection = $this->getProductByCategories($this->getCategoryIds(), $attribute) ?>
<?php $builderHelper = $this->helper('MGS\Fbuilder\Helper\Data'); ?>
<?php $template = 'MGS_Fbuilder::products/deals/grid_item.phtml'; ?>


<div class="content-block deals-product-cat-block">
	<?php // Block Content  ?>
	<?php if ($_productCollection->getSize()>0): ?>
		
		<?php $blockId = rand() . time(); ?>
		<?php $useSlider = $this->getUseSlider(); ?>
		
		<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
			<?php $slideMultiRow = true; ?>
			<?php $slideBy = 1 ?>
			<?php $columnCount = $perRowDefault * $this->getNumberRow(); ?>
		<?php else: ?>
			<?php $slideBy = $this->getSlideBy() ?>
			<?php $slideMultiRow = false; ?>
		<?php endif ?>
		<div class="block widget mgs-products deals-products-grid products-grid product-items">
			<div id="deals-products<?php echo $blockId; ?>" class="items  line row-<?php echo $perRowDefault ?>">
				<?php if($useSlider): ?>
					<amp-carousel class="product-carousel" height="270" width="300" layout="responsive" type="slides" autoplay delay="5000">
				<?php endif ?>
					<?php $i=0; $j=0; foreach ($_productCollection as $_product): $i++; ?>
						<div class="product product-item<?php if($slideMultiRow || !$this->hasData('number_row')): ?> col<?php endif ?>">
							<?php echo $this->getLayout()
								->createBlock('MGS\Fbuilder\Block\Products\ProductItem')
								->setLoadProduct($_product)
								->setBlockData($this->getData())
								->setTemplate($template)
								->toHtml(); ?>
											
						</div>
					<?php endforeach; ?>
				<?php if($useSlider): ?>
				</amp-carousel>
				<?php endif ?>
			</div>
		</div>
	<?php else: ?>
		<div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
	<?php endif ?>
</div>