<?php $tabs = $this->getTabs() ?>
<?php $labels = $this->getLabels() ?>

<div class="content-block mgs-product-tab">
	<?php $blockId = rand() . time(); ?>
	<?php $useAjax = $this->getUseAjax(); ?>
	<?php $items = $perRowDefault = $this->getPerrow(); ?>
	<?php $perRowTablet = $this->getPerrowTablet(); ?>
	<?php $perRowMobile = $this->getPerrowMobile(); ?>

	<?php $extraClass = 'tab-'.$this->getTabStyle().' tab-align-'.$this->getTabAlign() ?>
	<?php if($this->getTabFontBold()): ?>
		<?php $extraClass .= ' tab-font-bold' ?>
	<?php endif ?>
	<?php if($this->getTabItalic()): ?>
		<?php $extraClass .= ' tab-italic' ?>
	<?php endif ?>
	<?php if($this->getTabUppercase()): ?>
		<?php $extraClass .= ' tab-uppercase' ?>
	<?php endif ?>
	
	<div class="product data items mgs-tab <?php echo $extraClass?>" >
		
		<amp-accordion disable-session-states animate class="accordion product-accordion">
		<?php $i=0; foreach($tabs as $key=>$tab): ?>
			<?php if(isset($labels[$key])): $i++; ?>
				<section<?php if($i==1): ?> expanded<?php endif ?>>
					<h3 class=" accordion-header"<?php if($i==1): ?> aria-expanded="true"<?php endif ?>><?php echo $labels[$key]; ?></h3>
					<?php 
						switch ($tab){
							case "mgs_new_products_tabs":
								$blockClass = 'MGS\Fbuilder\Block\Products\NewProducts';
								$type = 'new';
								$attribute = NULL;
								break;
							case "mgs_sale_products_tabs":
								$blockClass = 'MGS\Fbuilder\Block\Products\Sale';
								$type = 'sale';
								$attribute = NULL;
								break;
							case "mgs_rate_products_tabs":
								$blockClass = 'MGS\Fbuilder\Block\Products\Rate';
								$type = 'rate';
								$attribute = NULL;
								break;
							default:
								$blockClass = 'MGS\Fbuilder\Block\Products\Attributes';
								$type = $attribute = $tab;
								break;
						}
						
						$html = $this->getLayout()
							->createBlock($blockClass)
							->setData($this->getData())
							->setAttribute($attribute)
							->setTabAttribute($attribute)
							->setTabType($type)
							->setTemplate('MGS_Amp::MGS_Fbuilder/products/tabs/items.phtml')
							->toHtml();
						if(!$useAjax){
							echo $html;
						}
					?>
				</section>
			<?php endif ?>
		<?php endforeach ?>
		</amp-accordion>
	</div>
</div>