<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $objTemplate */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $objTemplate \Magento\Customer\Block\Form\Login
 */
?>

<?php
    $helperConfig = $this->helper('MGS\MollaTheme\Helper\Config');
    $objTemplate = $helperConfig->createObjBlock('Magento\Customer\Block\Form\Register');
?>

<div class="frame">
    <div class="line">
        <div class="form-box block block-customer-login">
        <div class="form-tab">
            <ul class="nav nav-pills nav-fill block-title" role="tablist">
                <li class="nav-item">
                    <h2 class="title nav-link active" id="block-customer-login" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></h2>
                </li>
                <!--<li class="nav-item">
                    <h2 class="title nav-link" id="block-customer-register" role="heading" aria-level="2"><span><?php /*/* @escapeNotVerified */ /*echo __('Register') */?></span></h2>
                </li>-->
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade block-content active show" id="signin-2" role="tabpanel" aria-labelledby="signin-tab-2">
                    <form class="form form-login"
                          action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                          method="post"
                          id="login-form"
                          data-mage-init='{"validation":{}}'>
                        <?= $block->getBlockHtml('formkey'); ?>
                        <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                            <div class="form-group field email required">
                                <div class="form-group">
                                    <label for="login[username]" class="label required"><?= __('Username or email address'); ?><em> *</em></label>
                                    <div class="control">
                                        <input name="login[username]" value="<?= $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                                    </div>
                                </div>
                            </div>


                            <div class="form-group field password required">
                                <div class="form-group">
                                    <label for="login[username]" class="label required"><?= __('Password'); ?><em> *</em></label>
                                    <div class="control">
                                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
                                        <span class="fa fa-eye-slash icon" id="icon_camb"></span>    
                                    </div>
                                </div>

                           </div>
                           <div class="form-footer">
                                <?= $block->getChildHtml('form_additional_info'); ?>
                                <div class="btn-control-login">
                                    <div class="actions-toolbar padding-top10">
                                        <button type="submit" class="action login btn  btn-default  btn-rounded icon-right" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('LOG IN') ?></span></button>
                                    </div>
                                    <a class="remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a>
                                </div>
                           </div>

                        </fieldset>
                    </form>
                </div>
               <div class="tab-pane fade block-content" id="register-2" role="tabpanel" aria-labelledby="register-tab-2">
                    <?= $objTemplate->getChildHtml('form_fields_before')?>
                    <?php /* Extensions placeholder */ ?>
                    <?= $objTemplate->getChildHtml('customer.form.register.extra')?>
                    <form class="form create account form-create-account" action="<?php /* @escapeNotVerified */ echo $objTemplate->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
                        <fieldset class="fieldset create info">
                            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend><br>
                            <?= $objTemplate->getBlockHtml('formkey'); ?>
                            <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $objTemplate->getSuccessUrl() ?>">
                            <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $objTemplate->getErrorUrl() ?>">
                            <?= $objTemplate->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($objTemplate->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                            <?php if ($objTemplate->isNewsletterEnabled()): ?>
                                <div class="field choice newsletter">
                                    <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($objTemplate->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                                    <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
                                </div>
                                <?php /* Extensions placeholder */ ?>
                                <?= $objTemplate->getChildHtml('customer.form.register.newsletter')?>
                            <?php endif ?>

                            <?php $_dob = $objTemplate->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                            <?php if ($_dob->isEnabled()): ?>
                                <?= $_dob->setDate($objTemplate->getFormData()->getDob())->toHtml() ?>
                            <?php endif ?>

                            <?php $_taxvat = $objTemplate->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                            <?php if ($_taxvat->isEnabled()): ?>
                                <?= $_taxvat->setTaxvat($objTemplate->getFormData()->getTaxvat())->toHtml() ?>
                            <?php endif ?>

                            <?php $_gender = $objTemplate->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                            <?php if ($_gender->isEnabled()): ?>
                                <?= $_gender->setGender($objTemplate->getFormData()->getGender())->toHtml() ?>
                            <?php endif ?>
                        </fieldset>
                        <?php if ($objTemplate->getShowAddressFields()): ?>
                            <fieldset class="fieldset address">
                                <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend><br>
                                <input type="hidden" name="create_address" value="1" />
                                <div class="field company">
                                    <label for="company" class="label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                                    <div class="control">
                                        <input type="text" name="company" id="company" value="<?= $objTemplate->escapeHtml($objTemplate->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                                    </div>
                                </div>
                                <div class="field telephone">
                                    <label for="telephone" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                                    <div class="control">
                                        <input type="text" name="telephone" id="telephone" value="<?= $objTemplate->escapeHtml($objTemplate->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                                    </div>
                                </div>

                                <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

                                <div class="field street required">
                                    <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                                    <div class="control">
                                        <input type="text" name="street[]" value="<?= $objTemplate->escapeHtml($objTemplate->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                        <div class="nested">
                                            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                            <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                                <div class="field additional">
                                                    <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Address') ?></span>
                                                    </label>
                                                    <div class="control">
                                                        <input type="text" name="street[]" value="<?= $objTemplate->escapeHtml($objTemplate->getFormData()->getStreetLine($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                                    </div>
                                                </div>
                                            <?php endfor; ?>
                                        </div>
                                    </div>
                                </div>

                                <div class="field required">
                                    <label for="city" class="label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
                                    <div class="control">
                                        <input type="text" name="city" value="<?= $objTemplate->escapeHtml($objTemplate->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                                    </div>
                                </div>

                                <div class="field region required">
                                    <label for="region_id" class="label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                                    <div class="control">
                                        <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                                            <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                                        </select>
                                        <input type="text" id="region" name="region" value="<?= $objTemplate->escapeHtml($objTemplate->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                                    </div>
                                </div>

                                <div class="field zip required">
                                    <label for="zip" class="label"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
                                    <div class="control">
                                        <input type="text" name="postcode" value="<?= $objTemplate->escapeHtml($objTemplate->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                                    </div>
                                </div>

                                <div class="field country required">
                                    <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                                    <div class="control">
                                        <?= $objTemplate->getCountryHtmlSelect() ?>
                                    </div>
                                </div>
                                <?php $addressAttributes = $objTemplate->getChildBlock('customer_form_address_user_attributes');?>
                                <?php if ($addressAttributes): ?>
                                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                                    <?php $objTemplate->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                                    <?= $addressAttributes->setShowContainer(false)->toHtml()?>
                                <?php endif;?>
                                <input type="hidden" name="default_billing" value="1">
                                <input type="hidden" name="default_shipping" value="1">
                            </fieldset>
                        <?php endif ?>
                        <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Sign-in Information') ?></span></legend><br>
                            <div class="field required">
                                <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                                <div class="control">
                                    <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $objTemplate->escapeHtml($objTemplate->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                                </div>
                            </div>
                            <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                                <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                                <div class="control">
                                    <input type="password" name="password" id="password"
                                           title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                                           class="input-text"
                                           data-password-min-length="<?= $objTemplate->escapeHtml($objTemplate->getMinimumPasswordLength()) ?>"
                                           data-password-min-character-sets="<?= $objTemplate->escapeHtml($objTemplate->getRequiredCharacterClassesNumber()) ?>"
                                           data-validate="{required:true, 'validate-customer-password':true}"
                                           autocomplete="off">
                                    <div id="password-strength-meter-container" data-role="password-strength-meter" >
                                        <div id="password-strength-meter" class="password-strength-meter">
                                            <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                                            <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                                                <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="field confirmation required">
                                <label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label>
                                <div class="control">
                                    <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                                </div>
                            </div>
                            <?= $objTemplate->getChildHtml('form_additional_info'); ?>
                        </fieldset>
                        <?= $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('MGS_GDPR::customer/form/register.phtml')->toHtml(); ?>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button disabled type="submit" class="action submit primary btn  btn-default  btn-rounded icon-right" title="<?php /* @escapeNotVerified */ echo __('Sign Up') ?>"><span><?php /* @escapeNotVerified */ echo __('SIGN UP') ?></span></button>
                            </div>
                            <div class="secondary">
                                <a class="action back" href="<?= $objTemplate->escapeUrl($objTemplate->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Have an account?') ?></span></a>
                            </div>
                        </div>
                    </form>
                   </div>
            </div>
        </div>
        <div class="after-login-block">
            <div class="after-login-block__container">
                <h4>Nuevos clientes</h4>
                <p>Solicitar el registro le va a permitir comprar productos mediante la tienda virtual, comparar precios, ver disponibilidades y muchas otras cosas.</p>
                <a href="<?= $this->getUrl('customer/account/create'); ?>" class="btn">Solicitar el registro para Siglo 21</a>
            </div>
        </div>
    </div>
    </div>
</div>

<script>
require([
    'jquery',
    'mage/mage'
], function($){

    $("#icon_camb").click(function () {

				var cambio = document.getElementById("pass");
				if(cambio.type == "password"){
				cambio.type = "text";
				$('.icon').removeClass('fa fa-eye-slash').addClass('fa fa-eye');
				}else{
				cambio.type = "password";
				$('.icon').removeClass('fa fa-eye').addClass('fa fa-eye-slash');
				}
	})

    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($objTemplate->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($objTemplate->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $objTemplate->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>

<script>
    require(["jquery"], function($){
        $("#block-customer-register").on('click', function() {
            $("#signin-2").removeClass(' active show');
            $("#register-2").addClass(' active show');
            $('.nav-link').removeClass('active');
            $(this).addClass('active');
        });
        $("#block-customer-login").on('click', function() {
            $("#signin-2").addClass(' active show');
            $("#register-2").removeClass(' active show');
            $('.nav-link').removeClass('active');
            $(this).addClass('active');
        });
    });
</script>

