<?php

use Magento\Framework\App\Action\Action;

$dataHelper = $this->helper('MGS\AjaxCart\Helper\Data');
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$viewMode = 'grid';
$image = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$_product = $this->getProduct();
if ($_product != false && !empty($_product)) {
	$_productNameStripped = $block->stripTags($_product->getName(), null, true);
	$productImage = $block->getImage($_product, $image);
}

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$configHelper = $this->helper('MGS\ThemeSettings\Helper\Config');
$hideName = $this->getData('hide_name');
$hideReview = $this->getData('hide_review');
$hidePrice = $this->getData('hide_price');
$hideAddCart = $this->getData('hide_addcart');
$hideAddCompare = $this->getData('hide_addcompare');
$hideWishlist = $themeSettingConfig->getStoreConfig('themesettings/catalog/wishlist_button');
$hideCompare = $themeSettingConfig->getStoreConfig('themesettings/catalog/compare_button');
$hideDescription = $this->getData('hide_description');
$templateStyle = $this->getData('style-template');
$blockData =  array(
	"fbuilder_days" => $this->getData('fbuilder_days'),
	"fbuilder_hours" => $this->getData('fbuilder_hours'),
	"fbuilder_minutes" => $this->getData('fbuilder_minutes'),
	"fbuilder_seconds" => $this->getData('fbuilder_seconds')
);

?>
<?php if ($_product != false && !empty($_product) && $_product->getId()) : ?>
	<div class="block widget mgs-product single-deal products-grid product-items product-item">
		<div class="product-item-info template-<?= $templateStyle; ?>">
			<?php if ($templateStyle == 3) : ?>
				<?php if(($hideWishlist!=1) ||($hideCompare!=1)): ?>
					<div class="product-item-actions">
						<div data-role="add-to-links" class="actions-secondary">
							<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && ($hideWishlist!=1)): ?>
								<a href="#" class="action towishlist"  aria-label="<?= __('Save') ?>" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' data-action="add-to-wishlist" role="button">
									<span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
								</a>
							<?php endif; ?>
							<?php if($hideCompare!=1): ?>
								<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
								<a href="#" class="action tocompare" title="<?= $block->escapeHtml(__('Compare')) ?>" aria-label="<?= $block->escapeHtml(__('Compare')) ?>" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product) ?>' role="button">
									<span><?= /* @escapeNotVerified */ __('Compare') ?></span>
								</a>
							<?php endif ?>
						</div>
					</div>
				<?php endif ?>
				<div class="product top product-item-images">
					<a class="product-image product-item-link" href="<?= $_product->getProductUrl() ?>" title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>">
						<?= $productImage->toHtml() ?>
					</a>
				</div>
				<?php if ($this->getData('sub_title')) : ?>
					<div class="product label">
						<div class="sub-title"><?= $this->getData('sub_title'); ?></div>
					</div>
				<?php endif ?>
				<div class="product details product-item-details">
					<?= $this->getLayout()->createBlock('MGS\Fbuilder\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Fbuilder::products/deals/time.phtml')->setBlockData($blockData)->toHtml() ?>
					<?php if ($hideName != 1) : ?>
						<h4 class="product name product-item-name">
							<a class="product-item-link" href="<?= $_product->getProductUrl() ?>" title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>">
								<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
							</a>
						</h4>
					<?php endif ?>

					<?php if ($hidePrice != 1) : ?>
						<?= $block->getProductPrice($_product) ?>
						<span class="text-price-label">
							<?php echo __('Price without TAX') ?>
						</span>
					<?php endif ?>

					<?php if ($hideReview != 1) : ?>
						<?= $block->getReviewsSummaryHtml($_product, $templateType, true) ?>
					<?php endif ?>

					<?= $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>

					<?php if ($hideDescription != 1) : ?>
						<?php $shortDescription = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
						<?php if ($this->getData('truncate') && ($this->getData('truncate') > 0)) : ?>
							<?php $shortDescription = $configHelper->truncateString(strip_tags($shortDescription), $this->getData('truncate')) ?>
						<?php endif ?>
						<?php if ($shortDescription) : ?>
							<div class="product description product-item-description">
								<?= $shortDescription ?>
							</div>
						<?php endif ?>
					<?php endif; ?>
					<?php if (($hideAddCart != 1)) : ?>
						<div class="product-item-inner">
							<div class="product actions product-item-actions">
								<div class="actions-primary">
									<?php if ($_product->isSaleable()) : ?>
										<?php $postParams = $block->getAddToCartPostParams($_product); ?>
										<form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
											<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
											<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
											<?= $block->getBlockHtml('formkey') ?>
											<button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action tocart btn-default-dark">
												<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
											</button>
										</form>
									<?php endif; ?>
								</div>
							</div>
						</div>

					<?php else : ?>
						<div class="product-item-inner">
							<a href="<?= $_product->getProductUrl() ?>" title="<?= $block->escapeHtml(__('Shop Now')) ?>" class="action tocart primary">
								<span><?= /* @escapeNotVerified */ __('Shop Now') ?></span>
							</a>
						</div>
					<?php endif ?>
				</div>

			<?php else : ?>
				<div class="product details product-item-details">
					<?php if ($this->getData('sub_title')) : ?><div class="sub-title"><?= $this->getData('sub_title'); ?></div><?php endif ?>
					<?php if ($hideName != 1) : ?>
						<h4 class="product name product-item-name">
							<a class="product-item-link" href="<?= $_product->getProductUrl() ?>" title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>">
								<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
							</a>
						</h4>
					<?php endif ?>

					<?php if ($hidePrice != 1) : ?>
						<?= $block->getProductPrice($_product) ?>
						<span class="text-price-label">
							<?php echo __('Price without TAX') ?>
						</span>
					<?php endif ?>

					<?php if ($hideReview != 1) : ?>
						<?= $block->getReviewsSummaryHtml($_product, $templateType, true) ?>
					<?php endif ?>

					<?php if ($hideDescription != 1) : ?>
						<?php $shortDescription = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
						<?php if ($this->getData('truncate') && ($this->getData('truncate') > 0)) : ?>
							<?php $shortDescription = $configHelper->truncateString(strip_tags($shortDescription), $this->getData('truncate')) ?>
						<?php endif ?>
						<?php if ($shortDescription) : ?>
							<div class="product description product-item-description">
								<?= $shortDescription ?>
							</div>
						<?php endif ?>
					<?php endif; ?>
					<?php if ($templateStyle == 1) : ?>
						<?= $this->getLayout()->createBlock('MGS\Fbuilder\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Fbuilder::products/deals/time.phtml')->setBlockData($blockData)->toHtml() ?>
					<?php endif ?>

					<?php if (($hideAddCart != 1)) : ?>
						<div class="product-item-inner">
							<div class="product actions product-item-actions">
								<div class="actions-primary">
									<?php if ($_product->isSaleable()) : ?>
										<?php $postParams = $block->getAddToCartPostParams($_product); ?>
										<form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
											<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
											<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
											<?= $block->getBlockHtml('formkey') ?>
											<button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action tocart btn-default-dark  icon-right">
												<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
											</button>
										</form>
									<?php endif; ?>
								</div>
							</div>
						</div>
						<?php if ($templateStyle == 2) : ?>
							<?= $this->getLayout()->createBlock('MGS\Fbuilder\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Fbuilder::products/deals/time.phtml')->setBlockData($blockData)->toHtml() ?>
						<?php endif ?>

					<?php else : ?>
						<div class="product-item-inner">
							<a href="<?= $_product->getProductUrl() ?>" title="<?= $block->escapeHtml(__('Shop Now')) ?>" class="action default">
								<span><?= /* @escapeNotVerified */ __('Shop Now') ?></span>
							</a>
						</div>
					<?php endif ?>
				</div>
				<?php if ($templateStyle == 1) : ?>
					<div class="product images product-item-images">
						<a class="product-image product-item-link" href="<?= $_product->getProductUrl() ?>" title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>">
							<?= $productImage->toHtml() ?>
						</a>
					</div>
				<?php endif ?>
			<?php endif ?>
		</div>



	</div>
<?php else : ?>
	<div class="message info empty">
		<div><?= /* @escapeNotVerified */ __('There are no products matching the selection.') ?></div>
	</div>
<?php endif ?>
