<?php $builderHelper = $this->helper('MGS\Fbuilder\Helper\Data'); ?>
<?php $blogHelper = $this->helper('MGS\Blog\Helper\Data'); ?>
<?php $posts = $this->getPostCollection() ?>
<div class="content-block latest-post-grid-block">
	<?php if ($posts->getSize()>0): ?>
		<?php $blockId = rand() . time(); ?>
		<?php $useSlider = $this->getUseSlider(); ?>
		<?php $items = $perRowDefault = $this->getPerrow(); ?>
		<?php $perRowTablet = $this->getPerrowTablet(); ?>
		<?php $perRowMobile = $this->getPerrowMobile(); ?>
		<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
			<?php $slideMultiRow = true; ?>
			<?php $slideBy = 1 ?>
			<?php $columnCount = $perRowDefault * $this->getNumberRow(); ?>
		<?php else: ?>
			<?php $slideBy = $this->getSlideBy() ?>
			<?php $slideMultiRow = false; ?>
		<?php endif ?>
		
		<?php if($useSlider): ?>
			<amp-carousel class="blog-carousel" height="65" width="100" layout="responsive" type="slides"<?php if($this->getAutoplay()): ?> autoplay delay="5000"<?php endif ?><?php if($this->getNavigation()):?> controls<?php endif ?>>
				<?php $width=$height=$i=$j=0; foreach ($posts as $_post): $i++; ?>
					<div class="post-item">
						<?php if(!$this->getHideThumbnail()): ?>
							<?php $imageUrl = $_post->getThumbnailUrl() ?>
							<?php 
								try{
									list($width, $height, $type, $attr) = getimagesize(str_replace('https://','http://',$imageUrl));
								}catch(Exception $e){}
							?>
							<div class="thumbnail-post">
								<a href="<?php echo $_post->getPostUrlWithNoCategory(); ?>" title="<?php echo strip_tags($_post->getTitle()) ?>">
									<amp-img width="<?= $width ?>" height="<?= $height ?>" layout="responsive"alt="<?php echo strip_tags($_post->getTitle()) ?>" src="<?php echo $_post->getThumbnailUrl() ?>"></amp-img>
								</a>
							</div>
						<?php endif ?>
						<div class="post-item-detail">
							<div class="post-content">
								<h3 class="title-blog">
									<a href="<?php echo $_post->getPostUrlWithNoCategory(); ?>" title="<?php echo strip_tags($_post->getTitle()); ?>"><?php echo $_post->getTitle() ?></a>
								</h3>
								<?php if(!$this->getHideCreate()): ?>
									<div class="post-create-date">
										<?php echo __('By <span class="color-theme">%1</span> on %2', $_post->getUser(), date('M d, Y', strtotime($_post->getCreatedAt()))) ?>
									</div>
								<?php endif ?>
							</div>
							<?php if(!$this->getHideDescription()): ?>
								<div class="short-content">
									<?php echo $blogHelper->truncateString(strip_tags($_post->getShortContent()), $this->getCharacterCount()); ?>
								</div>
							<?php endif ?>
						</div>
					</div>
				<?php endforeach; ?>
			</amp-carousel>
		<?php else: ?>
		<div class="block widget mgs-post">
			<div id="post-<?php echo $blockId; ?>" class="items">
				<?php $width=$height=$i=$j=0; foreach ($posts as $_post): $i++; ?>
					<div class="post-item">
							<?php if(!$this->getHideThumbnail()): ?>
							
								<div class="thumbnail-post">
									<a href="<?php echo $_post->getPostUrlWithNoCategory(); ?>" title="<?php echo strip_tags($_post->getTitle()) ?>">
										<amp-img width="560" height="300" layout="responsive" alt="<?php echo strip_tags($_post->getTitle()) ?>" src="<?php echo $_post->getThumbnailUrl() ?>"></amp-img>
									</a>
								</div>
							<?php endif ?>
							<div class="post-item-detail">
								<div class="post-content">
									<h3 class="title-blog">
										<a href="<?php echo $_post->getPostUrlWithNoCategory(); ?>" title="<?php echo strip_tags($_post->getTitle()); ?>"><?php echo $_post->getTitle() ?></a>
									</h3>
									<?php if(!$this->getHideCreate()): ?>
										<div class="post-create-date">
											<?php echo __('By <span class="color-theme">%1</span> on %2', $_post->getUser(), date('M d, Y', strtotime($_post->getCreatedAt()))) ?>
										</div>
									<?php endif ?>
								</div>
								<?php if(!$this->getHideDescription()): ?>
									<div class="short-content">
										<?php echo $blogHelper->truncateString(strip_tags($_post->getShortContent()), $this->getCharacterCount()); ?>
									</div>
								<?php endif ?>
							</div>
						</div>
				<?php endforeach; ?>
			</div>
		</div>
		<?php endif ?>
	<?php else: ?>
		<div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find post matching the selection.') ?></div></div>
	<?php endif ?>
</div>