<?php 
	$builderHelper = $this->helper('MGS\Fbuilder\Helper\Data');
	$configHelper = $this->helper('MGS\Amp\Helper\Config');
	$html = $this->getHtmlSlider();
?>
<?php if($html != ""): ?>
	<?php
	$widthCarousel = $heightCarousel = 0;
	$domd = new DOMDocument();
	libxml_use_internal_errors(true);
	$domd->loadHTML($builderHelper->decodeHtmlTag($html), LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
	libxml_use_internal_errors(false);
	$domx = new \DOMXPath($domd);
	$itemsImg = $domx->query("//img[@src]");
	foreach($itemsImg as $imgItem) {
		list($width, $height, $type, $attr) = getimagesize(str_replace('https://', 'http://', $imgItem->getAttribute("src")));
		$widthCarousel = $width;
		$heightCarousel = $height;
		break;
	}
	unset($domd);
	?>
    <amp-carousel class="slider_mgs_carousel" autoplay delay="2000" width="<?= $widthCarousel ?>" height="<?= $heightCarousel ?>" layout="responsive" type="slides">
		<?= $configHelper->convertHtmlForAmp($builderHelper->decodeHtmlTag($html)); ?>
    </amp-carousel>
<?php else: ?>
	<div role="alert" class="alert alert-warning"><?= __('There are no sliders matching the selection.') ?></div>
<?php endif ?>