<?php
	$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
	$themeHelper = $this->helper('MGS\Fbuilder\Helper\Data');
	$footerVer = $themeSettingConfig->getStoreConfig('themesettings/footer/footer_version');
	$footerParallax = $themeSettingConfig->getStoreConfig('themesettings/footer/parallax');
	if($footerVer == ''){ $footerVer = 'footer1'; }
	if($themeSettingConfig->getStoreConfig('themesettings/footer/footer_bottom_custom_copyright')){
		$copyright = $themeSettingConfig->getStoreConfig('themesettings/footer/footer_bottom_copyright');
	}else {
		$copyright = $block->getChildHtml('copyright');
	}
?>

<?php if(!strpos($_SERVER['REQUEST_URI'], 'outsourcing')): ?>
		<style>
			button::-moz-focus-inner { border: 0; } /* Para Firefox */

			.boton3d{
				font-family:"Montserrat";
				border:0;
				color: #fff;
				font-size: 14px;
				padding: 18px 30px; /* Relleno del boton */
				letter-spacing: 2px; /* Espacio entre letras */
				background: #1C2656;
				-moz-border-radius: 10px;
				-webkit-border-radius: 10px;
				position: fixed;
				bottom: 30px;
				right: 10px;
				transition: all 300ms ease 0ms;
				box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
				z-index: 99;
				cursor: pointer;
				opacity: 0.7:
			}


			.boton3d:hover {
				background: -moz-linear-gradient(center top , #d3565d 0%, #d12c35 100%) repeat scroll 0 0 transparent;
				background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#d3565d), color-stop(100%,#cf2d35));
				color: #fff !important; /* Color del texto */
				opacity: 1:
			}
			
			@media only screen and (max-width: 600px) {
				.boton3d {
					font-size: 12px;
					padding: 12px 20px;
					bottom: 20px;
					right: 20px;
					
				}
			}
		</style>
	<a  title="OUTSOURCING" href="https://www.siglo21.net/outsourcing" target="_blank"><button class="boton3d" id="botonflotante"><i class="fas fa-store"></i>&nbsp OUTSOURCING</button></a>


	<script type="text/javascript">
			require([
				'jquery'
			],  function ($) {
				var dfUrl = '//cdn.doofinder.com/media/js/doofinder-classic.7.latest.min.js';
				(function(c,o,k,e){var r,t,i=setInterval(function(){t+=c;r=typeof(require)==='function';
					if(t>=o||r)clearInterval(i);if(r)require([k],e)},c)})(100, 10000, dfUrl, function(doofinder){
					doofinder.classic.setLayers([{
					"hashid": "c0c15a0029b6ae7b857597d4e08165bb",
					"zone": "us1",
					"display": {
						"results": {
							"initialLayout": "list"
						},
						"lang": "es"
					},
					"toggleInput": "#search",
					"queryInput": "#search"
					}]);
				});

					function myFunction(x) {
						var ahora= $('#botonflotante');
						if (x.matches) { // If media query matches
							
							ahora.html('<i class="fas fa-globe">');
						} else {
							ahora.html('<i class="fas fa-globe"></i>&nbsp OUTSOURCING');
						}
					}

					var x = window.matchMedia("(max-width: 600px)");
					myFunction(x) // Call listener function at run time
					x.addListener(myFunction) // Attach listener function on state changes
			});
	</script>
<?php endif ?>

<div id="footer-section" class="<?= $footerVer ?><?php if($footerVer == 'footer4' || $footerVer == 'footer6'): ?> footer-dark<?php endif ?><?php if($footerParallax): ?> footer footer-parallax<?php endif ?>">
	<?php if($footerVer == 'footer1'): ?>
		<div class="middle-footer">
			<div class="frame">
            	<div class="line">
            		<div class="col-mb-12 col-des-6 col-sm-12 col-tb-12">
            			<div class="widget widget-about">
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-block-logo')->toHtml(); ?>
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-about')->toHtml(); ?>
            				
            			</div><!-- End .widget about-widget -->
            		</div><!-- End .col-mb-12 col-des-3 -->

            		<div class="col-mb-12 col-des-2 col-sm-6 col-tb-4">
            			<div class="widget">
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-info')->toHtml(); ?>
            			</div><!-- End .widget -->
            		</div><!-- End .col-mb-4 col-des-3 -->
					<div class="col-mb-12 col-des-2 col-sm-6 col-tb-4">
						<?php $isLogged = $this->helper('Aventi\ManagerPrice\Helper\Data')->_getIsLogged();
						if($isLogged): ?>
								<div class="widget">
									<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-customer-service')->toHtml(); ?>
								</div><!-- End .widget -->
						<?php endif ?>
					</div><!-- End .col-mb-4 col-des-3 -->

            		<div class="col-mb-12 col-des-2 col-sm-6 col-tb-4">
            			<div class="widget">
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-my-account')->toHtml(); ?>
            			</div><!-- End .widget -->
            		</div><!-- End .col-mb-64 col-des-3 -->
            	</div><!-- End .line -->
            </div>
		</div>
		<div class="bottom-footer">
			<div class="frame">
        		<p class="footer-copyright">
        			<?= $copyright ?>
        		</p><!-- End .footer-copyright -->
        		<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-menu')->toHtml(); ?>
        		
        		<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-social-media')->toHtml(); ?>
        	</div>
		</div>
	<?php elseif($footerVer == 'footer2'): ?>
		<div class="middle-footer">
			<div class="frame-fluid">
                <div class="line">
                    <div class="col-mb-12 col-des-4 col-tb-12 col-sm-12">
                        <div class="widget widget-about">
                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-block-logo')->toHtml(); ?>
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-about')->toHtml(); ?>
                        </div><!-- End .widget about-widget -->
                    </div><!-- End .col-mb-12 col-des-4 -->

                    <div class="col-mb-6 col-des-2 col-tb-4 col-sm-6">
                        <div class="widget">
                        	<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-2-block-useful-link')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-4 col-des-2 -->

                    <div class="col-mb-6 col-des-2 col-tb-4 col-sm-6">
                        <div class="widget">
                        	<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-customer-service')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-4 col-des-2 -->

                    <div class="col-mb-6 col-des-2 col-tb-4 col-sm-6">
                        <div class="widget">
                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-my-account')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-4 col-des-2 -->

                    <div class="col-mb-12 col-des-2 col-tb-6 col-sm-6">
                        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-2-block-newsletter')->toHtml(); ?>
                    </div><!-- End .col-mb-6 col-des-2 -->
                </div><!-- End .line -->
            </div>
		</div>
		<div class="bottom-footer">
			<div class="frame-fluid">
        		<p class="footer-copyright">
        			<?= $copyright ?>
        		</p><!-- End .footer-copyright -->
        		<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-menu')->toHtml(); ?>
        		
        		<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-social-media')->toHtml(); ?>
        	</div>
		</div>

	<?php elseif($footerVer == 'footer3'): ?>
		<div class="middle-footer">
			<div class="frame">
            	<div class="line">
            		<div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
            			<div class="widget widget-about">
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-block-logo')->toHtml(); ?>
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-3-block-about')->toHtml(); ?>
            			</div><!-- End .widget about-widget -->
            		</div><!-- End .col-mb-6 col-des-3 -->

            		<div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
            			<div class="widget">
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-2-block-useful-link')->toHtml(); ?>
            			</div><!-- End .widget -->
            		</div><!-- End .col-mb-6 col-des-3 -->

            		<div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
            			<div class="widget">
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-customer-service')->toHtml(); ?>
            				
            			</div><!-- End .widget -->
            		</div><!-- End .col-mb-6 col-des-3 -->

            		<div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
            			<div class="widget">
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-my-account')->toHtml(); ?>
            			</div><!-- End .widget -->
            		</div><!-- End .col-mb-6 col-des-3 -->
            	</div><!-- End .line -->
            </div>
		</div>
		<div class="bottom-footer">
        	<div class="frame">
        		<p class="footer-copyright">
        			<?= $copyright ?>
        		</p><!-- End .footer-copyright -->
        		<figure class="footer-payments">
        			<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-block-payment')->toHtml(); ?>
        		</figure><!-- End .footer-payments -->
        	</div><!-- End .container -->
        </div>
	<?php elseif($footerVer == 'footer4'): ?>
		<div class="middle-footer">
			<div class="frame">
                <div class="line">
                    <div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
                        <div class="widget widget-about">
                        	<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-block-logo')->toHtml(); ?>
            				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-4-block-about')->toHtml(); ?>
                        </div><!-- End .widget about-widget -->
                    </div><!-- End .col-mb-6 col-des-3 -->

                    <div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
                        <div class="widget">
                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-2-block-useful-link')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-6 col-des-3 -->

                    <div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
                        <div class="widget">
                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-customer-service')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-6 col-des-3 -->

                    <div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
                        <div class="widget">
                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-my-account')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-6 col-des-3 -->
                </div><!-- End .line -->
            </div>
		</div>
		<div class="bottom-footer">
			<div class="frame">
                <p class="footer-copyright">
                	<?= $copyright ?>
                </p><!-- End .footer-copyright -->
                <figure class="footer-payments">
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-block-payment')->toHtml(); ?>
                </figure><!-- End .footer-payments -->
            </div>
		</div>
	<?php elseif($footerVer == 'footer5'): ?>
		<div class="bottom-footer">
			<div class="frame">
                <p class="footer-copyright">
        			<?= $copyright ?>
        		</p><!-- End .footer-copyright -->
        		<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-menu')->toHtml(); ?>
        		
        		<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-social-media')->toHtml(); ?>
            </div>
		</div>
	<?php elseif($footerVer == 'footer6'): ?>
		<div class="middle-footer">
			<div class="frame">
                <div class="line">
                    <div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
                        <div class="widget widget-about">
                        	<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-block-about')->toHtml(); ?>
                        </div><!-- End .widget about-widget -->
                    </div><!-- End .col-mb-6 col-des-3 -->

                    <div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
                        <div class="widget">
                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-2-block-useful-link')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-6 col-des-3 -->

                    <div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
                        <div class="widget">
                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-customer-service')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-6 col-des-3 -->

                    <div class="col-mb-12 col-des-3 col-tb-6 col-sm-6">
                        <div class="widget">
                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-block-my-account')->toHtml(); ?>
                        </div><!-- End .widget -->
                    </div><!-- End .col-mb-6 col-des-3 -->
                </div><!-- End .line -->
            </div>
		</div>
		<div class="bottom-footer">
			<div class="frame">
                <div class="footer-payments">
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-block-payment')->toHtml(); ?>
                </div><!-- End .footer-payments -->
				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-6-block-logo')->toHtml(); ?>
				<p class="footer-copyright">
                	<?= $copyright ?>
                </p><!-- End .footer-copyright -->
            </div>
		</div>
	<?php endif ?>
</div>

	
