<?php
$helper = $this->helper('MGS\Guestwishlist\Helper\Data');
if($this->getWishlistParam()){
	$items = $helper->getWishlistItemCollection(NULL,$this->getWishlistParam());
}else {
	$items = $helper->getWishlistItemCollection();
}
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$image = 'wishlist_thumbnail';
?>

<div id="guest_wishlist_list" class="guest_wishlist_list products wrapper wishlist grid products-grid">
    <?php $iterator = 1; ?>
    <?php if (count($items)): ?>
		<form class="form-wishlist-items" id="wishlist-view-form" action="<?= $this->getUrl('guestwishlist/index/updateall'); ?>" method="post" novalidate="novalidate">
			<input type="hidden" id="guest_status" name="guest_status" value="1">
			<table class="table table-wishlist table-mobile">
		        <thead>
		            <tr>
		                <th><?= __('Product') ?></th>
		                <th><?= __('Price') ?></th>
		                <th><?= __('Stock Status') ?></th>
		                <th></th>
		            </tr>
		        </thead>
		        <?php foreach ($items as $item): ?>
		        	<?php
                    $_product = $item['product'];
                    $productUrl = $_product->getUrlModel()->getUrl($_product, []);
                    ?>
		        <tr>
		            
	                <td>
	                	<div class="product">
		                	<div class="product-media">
		                		<?php $productImage = $_imagehelper->init($_product, $image)->getUrl(); ?>
								<a class="product-item-photo" href="<?= $block->escapeUrl($productUrl) ?>" title="<?php $block->stripTags($_product->getName(), null, true); ?>">
								    
									<span class="product-image-container">
										<span class="product-image-wrapper" style="padding-bottom: 100%;">
											<img class="product-image-photo" src="<?= $productImage ?>" alt="<?= $block->stripTags($_product->getName(), null, true); ?>">
										</span>
									</span>

								</a>
							</div>
							<h3 class="product-item-name">
							    <a class="product-item-link" href="<?= $block->escapeUrl($productUrl) ?>"><?= $block->stripTags($_product->getName(), null, true); ?></a>
							</h3>
						</div>
	                   
	                </td>
	                <td>
	                	<div class="price-box price-configured_price">
	                		<p class="price-as-configured">
								<span class="price-container price-configured_price tax weee">
							        <span data-price-type="finalPrice" class="price-wrapper ">
										<span class="price"><?= $helper->formatPrice($_product->getFinalPrice()) ?></span>
									</span>
							    </span>
							</p>
						</div>
	                </td>
	                <td>
	                	<?php if ($_product->isAvailable()): ?>
						    <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
						        <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
						    </div>
						<?php else: ?>
						    <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
						        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
						    </div>
						<?php endif; ?>
	                </td>
	                <td>
	                	<div class="product-item-inner">
	                		<div class="box-tocart">
	                			<fieldset class="fieldset">

	                				<?php if ($_product->isSaleable()): ?>
	                					<?php if ($_product->getTypeId() == 'simple'):?>
	                						<div class="field qty">
	                							<label class="label">
	                								<span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
	                							</label>
												<div class="control">
													<button type="button"  class="minus"><i class="icon-minus"></i></button>
													<input type="number" data-role="qty" id="qty[<?= $_product->getId() ?>]" class="input-text qty" data-validate="{'required-number':true,'validate-greater-than-zero':true}" name="qty[<?= $_product->getId() ?>]" value="<?= $item['qty'] ?>">
													<button type="button"  class="plus"><i class="icon-plus"></i></button>
												</div>
											</div>
											<div class="product-item-actions">
												<div class="actions-primary">
													<button type="button" data-role="tocart" data-post='<?= $item['data_post'] ?>' title="<?= __('Add to Cart') ?>" data-item-id="<?= $item['item_id'] ?>" class="action primary tocart btn btn-default  btn-product btn-cart">
														<?= __('Add to Cart') ?>
													</button>
												</div>
											</div>
	                					<?php else: ?>
		                					<div class="product-item-actions">
									            <div class="actions-primary">
									                <a class="select-option action primary tocart btn btn-default  btn-product btn-cart" href="<?php echo $_product->getProductUrl(); ?>">Select option</a>
									            </div>
									        </div>
		                				<?php endif; ?> 
	                				<?php else: ?>
	                					<?php if ($_product->getIsSalable()): ?>
								            <p class="available stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
								                <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
								            </p>
								        <?php else: ?>
								            <p class="unavailable stock btn action tocart disabled" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
								                <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
								            </p>
								        <?php endif; ?>
	                				<?php endif; ?> 
	                			</fieldset>
	                		</div>
	                		<input type="hidden" id="item_id[<?= $_product->getId() ?>]" class="input-text qty" name="item_id[<?= $_product->getId() ?>]" value="<?= $item['item_id'] ?>">
	                		<div class="product-item-actions">
	                			<button class="btn-remove action delete" href="javascript:void(0);" data-action="remove-from-wishlist" data-url='<?= $helper->getDeleteItemParams($item, $_product, $block->stripTags($_product->getName(), null, true)) ?>'><span class="ti-trash"></span></button>
	                		</div>
	                	</div>
	                </td>
		           
		        </tr>
		        <?php endforeach; ?>  
		    </table>
            
			<div class="actions-toolbar">
				<button id="update_all_wishlist" type="submit" title="Update Wish List" class="action update btn-default btn">
					<span><?= __('Update Wish List') ?></span>
				</button>
			</div>
		</form>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>
