<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\Ctq\Block\Customer\FileUploader */
?>
<div data-role="aw-ctq-file-uploader"
     data-bind="scope: 'awCtqFileUploader'"
     class="aw-ctq-file-uploader__container"
     data-mage-init='{"Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>}'>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>