<?php
/**
 * Copyright 2020 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/** @var Aheadworks\Ca\Block\Customer\CreateCompanyButton $block */

//@codingStandardsIgnoreFile

?>
<div class="aw-block-new-company">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Company Account')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?= $block->escapeHtml(__('If you are a company representative, use this feature to be able to manage subaccounts and other B2B features.')) ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?=
                $block->escapeUrl($block->getCreatePageUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create a Company Account')) ?></span></a>
            </div>
        </div>
    </div>
</div>
